### ISSUE TITLE
Disabled user returns same error as wrong username/password combination

### ISSUE THREAD

**Issue by sebastienpattyn93** [juju/python-libjuju#104]
I am running libjuju from source and I noticed that I get the same error for 2 different situations.
When I try to connect with a wrong password for an enabled user I get the following output:
`error: invalid entity name or password`

But when I disable a user (`juju disable-user testuser`)I get the same output and the same error. Is this intended? A different error message might be better because now I don't know if my user is disabled or if I'm using the wrong credentials 

```
async def run(): 
    try:
        controller = Controller()
        await controller.connect(
            url,
            'testuser',
            'testpass')

    except JujuAPIError as e:
        print('error: {}'.format(e.message))
```

**Comment by johnsca** [comment]
Unfortunately, this message is coming from the controller itself and there's not much we can do about it in libjuju.  Please re-open this on https://bugs.launchpad.net/juju if it is a blocker for you.
