### ISSUE TITLE
Incorrect parsing of zones constraint

### ISSUE THREAD

**Issue by luissimas** [juju/python-libjuju#1050]
### Description

When deploying a bundle with the `zones` constraint in a machine, the deployment fails with the following error from the juju API:

```
juju.errors.JujuAPIError: json: cannot unmarshal string into Go struct field Value.params.constraints.zones of type []string
```

The problem seems to be that python-libjuju sends the `zones` key as a string instead of an array of strings, as juju expects. See: https://github.com/juju/juju/blob/3.6/core/constraints/constraints.go#L107.

### Urgency

Annoying bug in our test suite

### Python-libjuju version

3.4

### Juju version

3.4.2

### Reproduce / Test

```python
import asyncio
from juju.model import Model

bundle_file = "./bundle.yaml"

bundle = """
name: sample-bundle

series: jammy

machines:
  "0":
    constraints: zones=z-1

applications:
  postgresql:
    charm: postgresql
    channel: 14/stable
    num_units: 1
    to:
      - lxd:0
"""

async def main():
    with open(bundle_file, "w") as f:
        f.write(bundle)

    model = Model()
    await model.connect()
    await model.deploy(bundle_file)

asyncio.run(main())
```

**Comment by Aflynn50** [comment]
Hey @luissimas, we can't currently merge your contribution as the commit is not signed and our repo has a rule disallowing merges of unverified commits.

Would you be able to follow this [GitHub guide](https://docs.github.com/en/authentication/managing-commit-signature-verification) and force push a verified version of your commit?
