### ISSUE TITLE
Code failure when relation is a peer relation

### ISSUE THREAD

**Issue by gboutry** [juju/python-libjuju#1066]
juju 3.4.3
libjuju 3.5.0.0

Cannot call `app.related_applications()` because it fails when there is a peer relationship: 

The following line throws: `ValueError: not enough values to unpack (expected 2, got 1)`.
This only happens when the relation is a peer relation.

https://github.com/juju/python-libjuju/blob/b56963442a6deffe46ce1fb5cb41970344263649/juju/application.py#L72

**Comment by hmlanigan** [comment]
Closed prematurely by the bot.
