### ISSUE TITLE
Update CI to python3.12

### ISSUE THREAD

**Issue by Aflynn50** [juju/python-libjuju#1088]
### Description

It is currently impossible to merge PRs with the `/merge` command due to a dependency on a python3.11 which tox is now unable to install.

### Urgency

Casually reporting

### Python-libjuju version

2.9, 3.5

### Juju version

NA

### Reproduce / Test

```python
NA
```

**Comment by dimaqq** [comment]
I wonder if @jack-w-shaw fixed this or worked around it in some other way?

**Comment by james-garner-canonical** [comment]
Closed due to `/merge` working now (fixed in #1106 -- or earlier?).
