### ISSUE TITLE
Fix function signature for local_refresh

### ISSUE THREAD

**Issue by dimaqq** [juju/python-libjuju#1100]
### Description

The code assumes quite a lot about the arguments.
It seems that there are no users of the function today, because the arguments are kinda broken.

Folks work around by calling juju cli instead, e.g.:

```py
# oidc-gatekeeper-operator/tests/integration/test_charm.py
149-        print("Try to refresh stable charm to locally built")
150-        # temporary measure while we don't have a solution for this:
151-        # * https://github.com/juju/python-libjuju/issues/881
152:        # Currently `application.local_refresh` doesn't work as expected.
```

### Urgency

Casually reporting

### Python-libjuju version

any

### Juju version

any

### Reproduce / Test

```python
pyright
```

**Comment by dimaqq** [comment]
See 0771a65 for an attempt to do this.

**Comment by benhoyt** [comment]
@dimaqq Can you please be a bit more specific? What does it assume about the arguments, and what are the specific issues?

**Comment by dimaqq** [comment]
Function has None defaults for parameters that are actually required.

Users work around this function by shelling out because they can’t get a working set of arguments together.
