### ISSUE TITLE
`websockets` 14.0 breaks python-libjuju

### ISSUE THREAD

**Issue by NucciTheBoss** [juju/python-libjuju#1184]
### Description

The newest, major release of the `websockets` library - version 14.0 which was released on Saturday - is not compatible with `python-libjuju` and results in errors being thrown when attempting to use `python-libjuju` to drive Juju. Here's the relevant stacktrace when I attempt to run the Slurm charm integration tests using `pytest-operator`:

```pytb
Traceback (most recent call last):
  File "/home/ubuntu/slurm-charms/.tox/integration/lib/python3.12/site-packages/juju/client/connection.py", line 873, in _connect_with_login
    result = (await self.login())['response']
              ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/slurm-charms/.tox/integration/lib/python3.12/site-packages/juju/client/connection.py", line 970, in login
    return await self.rpc({
           ^^^^^^^^^^^^^^^^
  File "/home/ubuntu/slurm-charms/.tox/integration/lib/python3.12/site-packages/juju/client/connection.py", line 643, in rpc
    if self.monitor.status == Monitor.DISCONNECTED:
       ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/slurm-charms/.tox/integration/lib/python3.12/site-packages/juju/client/connection.py", line 224, in status
    if stopped or not connection._ws.open:
                      ^^^^^^^^^^^^^^^^^^^
AttributeError: 'ClientConnection' object has no attribute 'open'
```

Looking at _setup.py_, the required version of `websockets` has no upper-bound, so every new install of `python-libjuju` will pull in an incompatible version of `websockets`:

https://github.com/juju/python-libjuju/blob/a70983d802d90ee44a464fb87d2ad528f09c3be3/setup.py#L29

### Urgency

Blocker for our release

### Python-libjuju version

latest/stable

### Juju version

3.5.4-genericlinux-amd64

### Reproduce / Test

```python
# Assuming that you have tox, charmcraft, and the Juju CLI installed on your machine, and you
# have a Juju controller deployed for on an LXD undercloud.

$ git clone https://github.com/nuccitheboss/slurm-charms.git
$ cd slurm-charms && git checkout feat-impl-slurm-ops
$ tox run -e integration
# See Python stacktrace output with AttributeError's galore related to websockets 14.0 API change.
```

**Comment by james-garner-canonical** [comment]
This should be resolved in `main`, but we still need to get the fix into releases

**Comment by dimaqq** [comment]
Done in https://pypi.org/project/juju/3.5.2.1/
