### ISSUE TITLE
jujubot auto-reply on external PRs needs love

### ISSUE THREAD

**Issue by james-garner-canonical** [juju/python-libjuju#1188]
### Description

Current message:

> Thanks for opening a pull request! Please follow the instructions [here](https://github.com/juju/juju/blob/develop/CONTRIBUTING.md#tldr) to ensure your pull request is ready for review. Then, a maintainer will review your patch.
> 
> @hpidcock @anvial

Link 404s. The 'correct' link would be https://github.com/juju/juju/blob/main/doc/CONTRIBUTING.md, but even then there's a bunch of Juju specific information that doesn't apply here, such as "Bug reports should be filed on [Launchpad](https://bugs.launchpad.net/juju/+bugs), not GitHub".

We should link to python-libjuju [CONTRIBUTING.md](https://github.com/juju/python-libjuju/blob/main/docs/CONTRIBUTING.md) instead, but at the very least that should be updated to explain the juju conventional commits convention, e.g. linking [here](https://github.com/juju/juju/blob/main/doc/CONTRIBUTING.md#conventional-commits).

Also it seems to double post? (See [here](https://github.com/juju/python-libjuju/pull/1147) and [here](https://github.com/juju/python-libjuju/pull/1187)).

Also it should probably ping someone else, like @dimaqq and I.

### Urgency

Casually reporting

### Python-libjuju version

main

### Juju version

n/a

### Reproduce / Test

```python
...
```

**Comment by Srijan-SS02** [comment]
Hello @james-garner-canonical, it looks like the repository to jujubot is not a [public repository](https://github.com/jujubot?tab=repositories), or am I looking in the wrong place? 

Also, there is a slight typo in the doc for `git add upstream git@github.com:juju/python-libjuju.git` which should be `git remote add` [here](https://github.com/juju/python-libjuju/blob/main/docs/CONTRIBUTING.md#pull-request) 

Happy to contribute if there is any way you can provide access to the repo or direct me to the correct source if I am looking in wrong place.

**Comment by james-garner-canonical** [comment]
Thanks for taking an interest in this issue, @Srijan-SS02. Are you a user of python-libjuju?

I think you're right about jujubot, I suspect its configuration is private by design, so we'll have to fix this one internally.

Thanks for catching that docs typo! I'll take care of the docs portion of this shortly.

**Comment by hpidcock** [comment]
I've turned this off across all juju org projects.

**Comment by dimaqq** [comment]
Let's close this after next external PR when we're sure that the bot is gone.

**Comment by james-garner-canonical** [comment]
Thanks, Harry, that solves the issue.

@dimaqq  I'll update the PR template with the information we want new python-libjuju contributors to see -- conventional commits convention (names), requirement for signed commits and CLA, and that a maintainer will have to run `/build`. Anything else?

**Comment by Srijan-SS02** [comment]
> Thanks for taking an interest in this issue, @Srijan-SS02. Are you a user of python-libjuju?
> 
> I think you're right about jujubot, I suspect its configuration is private by design, so we'll have to fix this one internally.
> 
> Thanks for catching that docs typo! I'll take care of the docs portion of this shortly.

Hello @james-garner-canonical, I was exploring more about juju and found this repo of python-libjuju. Not a regular user but still happy to contribute.

**Comment by dimaqq** [comment]
@Srijan-SS02 there's whole bunch of "help-wanted" issues.

If you want to help, you'll need to set up Juju and LXD and/or MicroK8s. Some of it takes time, but there are docs and it's a great introduction to Canonical ecosystem.

I see that you're already involved with Ubuntu. Compared to that, the Juju world is oriented more towards production and attracts notably fewer users, which means relying on (and improving) official docs rather than, say, stackoverflow and more hard work in general. Totally worth trying, if you ask me!

**Comment by Srijan-SS02** [comment]
Hi @dimaqq Thanks, for the suggestion and the thoughtful encouragement! This sounds good and challenging to me, I definitely am going to give it a try. I have been more into DevOps and Python side so far in my career, so production work aligns with my skill set. 

Is there any official channel to communicate like slack or any other?

**Comment by dimaqq** [comment]
We’re all on matrix. It’s documented in docs/contributing.md
