### ISSUE TITLE
Missing websockets pin in libjuju 2.9.49.0

### ISSUE THREAD

**Issue by dragomirp** [juju/python-libjuju#1226]
### Description

Related to https://github.com/juju/python-libjuju/issues/1184

A pin for websockets was added to libjuju 3.5, but not to libjuju 2.9, so 2.9.49.0 will fail if websockets pin is not maintained elsewhere.

It fails with:
```
  File "/home/runner/work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/juju/client/connection.py", line 430, in close
    if self._ws and not self._ws.closed:
AttributeError: 'ClientConnection' object has no attribute 'closed'. Did you mean: 'close'?
```
CI runs can be seen [here](https://github.com/canonical/postgresql-operator/actions/runs/12066775292/job/33648667389?pr=664)

### Urgency

Annoying bug in our test suite

### Python-libjuju version

2.9.49.0

### Juju version

2.9.51

### Reproduce / Test

```python
# on juju 2.9 with libjuju 2.9.49.0
# python -m asyncio
import asyncio
from juju.model import Model
model = Model()
await model.connect_current()
```

**Comment by dimaqq** [comment]
I can release a 2.9.49.x, though you'll still have to update your CI workflow, because today it forces an exact version:

```
poetry add --lock --group integration juju@'==2.9.49.0
```

**Comment by dragomirp** [comment]
> I can release a 2.9.49.x, though you'll still have to update your CI workflow, because today it forces an exact version:
> 
> ```
> poetry add --lock --group integration juju@'==2.9.49.0
> ```

Hi, the renovate bot should move the CI pin for us once the new version is released, so that should be automatically handled on our end.

**Comment by dimaqq** [comment]
> [Juju 2.9](https://juju.is/docs/juju/roadmap#juju-juju-29)
> Currently in Security Fix Only support.

The same applies to python-libjuju.

In other words, the fact that `juju >= 3.6` release makes using `juju < 3` less convenient is just something we'll have to live with.

I would propose one of the following work-arounds, in reverse order of pedantry:
1. separate lock files for juju 2.x and 3.x
  a. clear pins for juju and dependencies
  b. independent Python version restriction
2. list `websockets < 14` dependency directly for both juju 2.x and 3.x

**Comment by taurus-forever** [comment]
@sinanawad as discussed with @jnsgruk today. Please reopen the issue and fix Juju 2.9. Tnx!

**Comment by benhoyt** [comment]
Charm Tech, the (temporary?) maintainers of python-libjuju, discussed this in our daily sync today, and @james-garner-canonical is going to put up a 2.9 release with this dependency fix today or tomorrow.

However, in general 2.9 Juju (and python-libjuju) is in "security updates only" mode, so please note that this isn't an open door to sneak features into 2.9 versions. :-)

**Comment by dimaqq** [comment]
Doen via https://github.com/juju/python-libjuju/pull/1235
