### ISSUE TITLE
Looking for the correct syntax to pass into "entities" to DestroyModels()

### ISSUE THREAD

**Issue by sfeole** [juju/python-libjuju#14]
In the ModelManagerFacade Class, there is a method to DestroyModels 

  ```
  @ReturnMapping(ErrorResults)
    async def DestroyModels(self, entities):
        '''
        entities : typing.Sequence<+T_co>[~Entity]<~Entity>
        Returns -> typing.Sequence<+T_co>[~ErrorResult]<~ErrorResult>
        '''
        # map input types to rpc msg
        _params = dict()
        msg = dict(type='ModelManager', request='DestroyModels', version=2, params=_params)
        _params['entities'] = entities
        reply = await self.rpc(msg)
        return reply
  ```

I wrote the glue in juju/controllers.py to interact with this..  Example Snippet

```
    async def destroy_model(self, entities):
        """Add a model to this controller to Destroy.

        :param str entities: Name of the model

        """
        model_facade = client.ModelManagerFacade()
        model_facade.connect(self.connection)

        log.debug('Creating model %s', entities)

        model_info = await model_facade.DestroyModels(entities)
```

When writing my script to interact with libjuju ,  I'm not sure what to pass into destroy_model()
What format should I be using? Is there a list of prefixes that I should be using, for example:

await controller.destroy_models(
           "model-" + string ? ) 

The error I see is:  juju.errors.JujuAPIError: json: cannot unmarshal string into Go value of type []params.Entity

**Comment by tvansteenburgh** [comment]
From the DestroyModels doc string, it looks like DestroyModels takes a sequence of client.Entity objects, so I'd try that, e.g.:

    await model_facade.DestroyModels([client.Entity('model-foo')])

You can infer that the 'model-' prefix is needed b/c client.Entity.__init__ takes a "tag". Prefixes for the different tag types (and how to make a tag from an entity name) can be found in https://github.com/juju/names.

**Comment by sfeole** [comment]
Thanks,  I found it,  [client.Entity('model-UUID')]

**Comment by tvansteenburgh** [comment]
@sfeole Great, put up a PR!
