### ISSUE TITLE
Handle dropped connections in the object-layer

### ISSUE THREAD

**Issue by johnsca** [juju/python-libjuju#150]
PR #148 added dropped connection handling for all of the background tasks and when first issuing API calls, but they can still be propagated up to the client if they occur after an API call has been issued but before the response has been received.  To handle this automatically, we have to make every object-layer method aware of the connection dropping issue and figure out how to determine if the API call needs to be reissued or not by re-inspecting the model after reconnect (with some delay, for operations that may take some time to show up in the model).

**Comment by juanmanuel-tirado** [comment]
This issue has expired.
