### ISSUE TITLE
Support for JaaS specific commands

### ISSUE THREAD

**Issue by tvanhove** [juju/python-libjuju#159]
Can we get support for the following JaaS related CLI calls in libjuju?

### Activate SLA
`juju sla <essential|standard|advanced> --budget <wallet-name>:<number>`
Essential is the only one supported right now. First time execution will require to accept the SLA, something like this:
`juju agree canonical/sla-terms/1`

### Overview of the wallets
`juju wallets`
Response:
```
Wallet          Monthly Budgeted        Available       Spent
primary*           1000      100            95.41        4.59
Total              1000      100            95.41        4.59
                                                             
Credit limit:      1000
```
### Set budget for wallet
`juju set-wallet <wallet-name> <number>`
Cannot be lower than the already budgeted credits.
Failed response:
> ERROR failed to set the wallet: wallet limit cannot be less than the sum of the budgets`

### Create wallet
`juju create-wallet <wallet-name>`

### Details of a wallet
`juju show-wallet <wallet-name>`
Response:
```
Model                   Spent   Budgeted           By   Usage
sla-prod:admin/cdk1     4.59         100        cmars   4%   
                                                     
Total                   4.59         100                4%   
Wallet                              1000             
Unallocated                          900             
```
### Set budget for current model
`juju budget <number>`
Cannot be lower than credits already spent.
Failed response:
> ERROR failed to update the budget: budget limit below current spend 4.59

Cannot be higher than wallet budget.
Failed response:
> ERROR failed to update the budget: budget limits cannot exceed the wallet limit

### Retrieve metrics
`juju metrics <application-name>`
Response:
```
UNIT        	           TIMESTAMP	    METRIC	VALUE
sojobo-api/0	2017-09-26T21:31:24Z	juju-units	    1
```
There is already a wrapper (not async) available, but not implemented ...
```
  def collect_metrics(self):
        """Collect metrics on this application.
        """
        raise NotImplementedError()
```

### Rating 
There is no command to retrieve the rating of a user to date containing all the spent credits on all the models for a certain month in a certain year. First time run requires Ubuntu SSO login.
API endpoint:
`https://api.jujucharms.com/omnibus/v3/u/{username}/rating/{yyyy}-{mm}`
Response:
```
{
        models: {
                "7ec613cf-b8f7-48a9-8e6e-055da691cc13": {
                        authorizations: { … }
                        machine-support: {
                                total: {
                                        price: "1.12"
                                }
                                rating: {
                                        price: "0.011"
                                        hours: {
                                                hour-2017_08_03_04: {
                                                        value: "6"
                                                        multiplier: "1"
                                                        total: "6"
                                                }
							… 
                                                hour-2017_08_03_20: {
                                                        value: "6"
                                                        multiplier: "1"
                                                        total: "6"
                                                }
                                        }
                                }
                        }
                        total: {
                                price: "1.12"
                        }
                }
… 
        }
}
```

**Comment by juanmanuel-tirado** [comment]
This issue has expired.
