### ISSUE TITLE
Always having an AllWatcher can be expensive on large models

### ISSUE THREAD

**Issue by johnsca** [juju/python-libjuju#181]
@rogpeppe brought up that having an AllWatcher running can get expensive on large models, especially if all you want to do is deploy and / or query the state of a single application, for instance.  Perhaps we can look into lazy-starting the watcher, having an option to use more fine-grained watchers (may require small changes to core), or some other approach.  At least it's worth doing some benchmarking against large models.

**Comment by juanmanuel-tirado** [comment]
This issue has expired.
