### ISSUE TITLE
model.info.uuid is no longer available after model.disconnect()

### ISSUE THREAD

**Issue by Cynerva** [juju/python-libjuju#199]
We had this snippet in our CDK integration tests fail after a recent upgrade of libjuju:

```
    await model.disconnect()
>   await controller.destroy_model(model.info.uuid)
E   AttributeError: 'NoneType' object has no attribute 'uuid'
```

Looks like a recent change made it where `model.disconnect()` sets `model.info` to None, here: https://github.com/juju/python-libjuju/blob/17dffa4563cabeb187e50512e58f330455f3065a/juju/model.py#L521

We fixed this easily enough by updating our code to destroy the model by name instead of UUID, but I'm confused. Why nuke model.info?

**Comment by johnsca** [comment]
@rogpeppe I saw this on your PR but didn't really think about it at the time.  Is there a reason to clean up that cached info on disconnect, or is it just bookkeeping that is maybe more useful to not do?

**Comment by rogpeppe** [comment]
I guess it's reasonably to leave info still currently. It seemed reasonable to clean it up on disconnect (the info is kinda not current after all) but I'd be happy to leave it there until it connected again.

**Comment by juanmanuel-tirado** [comment]
This issue has expired.
