### ISSUE TITLE
Package name conflicts with existing package on pypi

### ISSUE THREAD

**Issue by johnsca** [juju/python-libjuju#2]
https://pypi.python.org/pypi/juju

That appears to be a very old version of the Python implementation of juju.  We can probably reclaim the name from Kapil.

**Comment by tvansteenburgh** [comment]
I've emailed Kapil about this.

**Comment by sparkiegeek** [comment]
@tvansteenburgh think you can close this one now? https://pypi.python.org/pypi/juju is this codebase

**Comment by tvansteenburgh** [comment]
@sparkiegeek Yes, thanks!
