### ISSUE TITLE
Model.add_machine doesn't parse constraints

### ISSUE THREAD

**Issue by johnsca** [juju/python-libjuju#200]
We have logic for parsing constraints specs which is [used](https://github.com/juju/python-libjuju/blob/master/juju/model.py#L1273) in `Model.deploy()`, but it's [not used](https://github.com/juju/python-libjuju/blob/master/juju/model.py#L929-L930) in `Model.add_machine()`.

**Comment by juanmanuel-tirado** [comment]
This issue has expired.
