### ISSUE TITLE
Adding machines to manual cloud

### ISSUE THREAD

**Issue by sebastienpattyn93** [juju/python-libjuju#201]
I'm currently setting up a manual cloud and I bootstrapped the cloud already and added 2 machines to the cloud. Is there a way to add these machines to a cloud in libjuju, Any kind of wrapper that does the same as `juju add-machine ssh:ubuntu@192.168.1.129` Or any code in one of the facades? I can't really find one at the moment.

**Comment by sfeole** [comment]
bump, any plans to get this integrated?  I'm working with s390x systems, and can only use juju manual provider for the time being, would be nice to get libjuju working since I can use scripts that I already have to do various tests.

**Comment by sfeole** [comment]
@sebastienpattyn93  I just found this:   [DOCS](https://pythonlibjuju.readthedocs.io/en/latest/api/juju.model.html?highlight=manual#juju.model.Model.add_machine
)
Use the Spec Param:  add_machine(spec="ssh:user@10.10.0.3")

**Comment by sebastienpattyn93** [comment]
@sfeole  Thank you... I wil try this later today

**Comment by sfeole** [comment]
@sebastienpattyn93  I could not get this to work, perhaps you did?

**Comment by johnsca** [comment]
This was fixed in #240
