### ISSUE TITLE
JujuData.models() does not reflect current running models , when created via juju.controller.addmodel

### ISSUE THREAD

**Issue by sfeole** [juju/python-libjuju#22]
After I create a new model with the following:

```
    controller = Controller()
    await controller.connect_current()

    model = await controller.add_model(
        'libjujutest',
        'cloud-localhost',
        'cloudcred-localhost_admin_default',
    )

```

I can easily deploy a charm as outlined in examples/controller.py

doing.

```
    await model.deploy(
        'ubuntu-0',
        service_name='ubuntu',
        series='xenial',
        channel='stable',
    )

```

However If I try to use methods from the juju.model library It appears as if the newly created model does not exist at least according to the api.

For Example: If I try to connect to the newly created model using this example below. (Which utilizes juju.model.ModelObserver() to run a series of tests)  I see an error.

```
async def run():
    controller = Controller()
    await controller.connect_current()

    await controller.add_model(
        'libjujutest',
        'cloud-localhost',
        'cloudcred-localhost_admin_default',
    )

    model = Model()
    await model.connect_model(
        'localhost-lxd:admin/libjujutest'
         )
    model.add_observer(MyModelObserver())
    await model.deploy(
        'ubuntu-0',
        service_name='ubuntu',
        series='xenial',
        channel='stable',
    )

```

> DEBUG:asyncio:Using selector: EpollSelector
> INFO:websocket:Driver connected to juju wss://10.0.8.157:17070/api
> DEBUG:LibJuju.juju.controller:Creating model libjujutest
> INFO:websocket:Driver connected to juju wss://10.0.8.157:17070/model/97153d75-564f-400d-88dd-db85e6009695/api
> DEBUG:LibJuju.juju.model:Starting watcher task
> INFO:websocket:Driver connected to juju wss://10.0.8.157:17070/model/97153d75-564f-400d-88dd-db85e6009695/api
> ERROR:asyncio:Task exception was never retrieved
> future: <Task finished coro=<run() done, defined at ./controller.py:39> exception=KeyError('admin/libjujutest',)>
> Traceback (most recent call last):
>   File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
>     result = coro.send(None)
>   File "./controller.py", line 52, in run
>     'localhost-lxd:admin/libjujutest'
>   File "/home/sfeole/git/hyperscale/lib/LibJuju/juju/model.py", line 375, in connect_model
>     self.connection = await connection.Connection.connect_model(arg)
>   File "/home/sfeole/git/hyperscale/lib/LibJuju/juju/client/connection.py", line 220, in connect_model
>     model_uuid = models['models'][model_name]['uuid']
> KeyError: 'admin/libjujutest'

If the model is created via the command line, "juju add-model FOO"  I usually don't see the problem when trying to run model.connect_controller(). And also found that juju.client.connections JuJuData.models() sees the model I created via the CLI.  But that defeats the purpose of using the api. 

I've looked in juju.cliient.client and juju.client.connections when I see this error.  It appears that  Jujudata.models()   knows nothing about the newly created model by juju.controller.add_model() 
If I query JuJuData.Models()  during the lifetime of the script, I never see the model, "libtest-juju"

```

In [10]: JUJU = connection.JujuData()

In [11]: JUJU.models()
Out[11]: 
{'localhost-lxd': {'models': {'admin/controller': {'uuid': 'cb782591-ebfe-44a4-8371-abe3943448db'},
   'admin/seantest': {'uuid': '2450573f-27ae-4dd3-81b6-37b293347ad2'},
   'admin/default': {'uuid': '4c5fd23c-d25a-4d84-8c93-fccd2a3089a8'}}}}

```

If I run juju list-models via the CLI,

```
Model        Cloud/Region         Status     Machines  Cores  Access  Last connection
controller   localhost/localhost  available         1      -  admin   just now
default      localhost/localhost  available         0      -  admin   4 hours ago
seantest*    localhost/localhost  available         0      -  admin   never connected
libjujutest  localhost/localhost  available         1      -  admin   5 minutes ago
```

There is the model, in fact alive and well and has machines attached and units "Ubuntu/0" which we deployed.
```

sfeole@sfmadmax:~$ juju switch libjujutest
localhost-lxd:admin/seantest -> localhost-lxd:admin/libjujutest
sfeole@sfmadmax:~$ juju status
Model        Controller     Cloud/Region         Version
libjujutest  localhost-lxd  localhost/localhost  2.0.2.1

App     Version  Status   Scale  Charm   Store       Rev  OS      Notes
ubuntu           unknown      1  ubuntu  jujucharms    0  ubuntu  

Unit       Workload  Agent  Machine  Public address  Ports  Message
ubuntu/0*  unknown   idle   0        10.0.8.28              

Machine  State    DNS        Inst id        Series  AZ
0        started  10.0.8.28  juju-38a03a-0  xenial  

```
By running juju switch <model>  I bring the model in focus, after doing so. I can now see the model in connection.JuJuData() and run my script after commenting out the "add_model()" method. 

Does the following code in juju.controllers.add_model() automatically bring the model "in focus" or "connect" to it after creation?

```
        model = Model()
        await model.connect(
            self.connection.endpoint,
            model_info.uuid,
            self.connection.username,
            self.connection.password,
            self.connection.cacert,
            self.connection.macaroons,
        )

        return model
```

**Comment by tvansteenburgh** [comment]
I haven't tested it but I'm curious if the code below works for you. Instead of instantiating a new Model directly, you should be able to just use the one returned from Controller.add_model().

```python
async def run():
    controller = Controller()
    await controller.connect_current()

    model = controller.add_model(
        'libjujutest',
        'cloud-localhost',
        'cloudcred-localhost_admin_default',
    )
    model.add_observer(MyModelObserver())
    await model.deploy(
        'ubuntu-0',
        service_name='ubuntu',
        series='xenial',
        channel='stable',
    )
```

**Comment by sfeole** [comment]
Thanks Tim,  That's it!   i was over-complicating the problem, closing this out.
