### ISSUE TITLE
Local charms fail on JaaS

### ISSUE THREAD

**Issue by johnsca** [juju/python-libjuju#221]
When connected to a JaaS model, [uploading local charms](https://github.com/juju/python-libjuju/blob/master/juju/model.py#L578) is failing due to macaroon auth issues.  Currently, it throws a `BrokenPipeError` because the macaroon [is not included in the headers](https://github.com/juju/python-libjuju/blob/master/juju/client/connection.py#L345-L346), but even with that resolved, it gets a discharge required error with no redirect info.

**Comment by juanmanuel-tirado** [comment]
This issue has expired.
