### ISSUE TITLE
unit.run fails if a timeout value is passed

### ISSUE THREAD

**Issue by thedac** [juju/python-libjuju#225]
unit.run with timeout=None succeeds:
REMOTE RUN: unit-get private-address timeout=None
REPLY: {'request-id': 7, 'response': {'results': [{'action': {'tag': 'action-009bdeea-ada7-47e8-8586-a876a4b6cf0b', 'receiver': 'unit-ubuntu-0', 'name': 'juju-run', 'parameters': {'command': 'unit-get private-address', 'timeout': 0}}, 'enqueued': '2018-04-12T16:36:26Z', 'started': '0001-01-01T00:00:00Z', 'completed': '0001-01-01T00:00:00Z', 'status': 'pending'}]}}
ACTION: {'model-uuid': '1a035018-71ff-473e-8aab-d1a8d6b6cda7', 'id': '009bdeea-ada7-47e8-8586-a876a4b6cf0b', 'receiver': 'ubuntu/0', 'name': 'juju-run', 'parameters': {'command': 'unit-get private-address', 'timeout': 0}, 'status': 'completed', 'message': '', 'results': {'Code': '0', 'Stderr': '', 'Stdout': '10.5.0.97\n'}, 'enqueued': '2018-04-12T16:36:26Z', 'started': '2018-04-12T16:36:26Z', 'completed': '2018-04-12T16:36:26Z'}

unit.run with timeout = 300 (or any integer) fails with "command cancelled":
300s TIMEOUT
REMOTE RUN: unit-get private-address timeout=300
REPLY: {'request-id': 7, 'response': {'results': [{'action': {'tag': 'action-67eb94dc-f8a0-4333-878e-fbabf77862a5', 'receiver': 'unit-ubuntu-0', 'name': 'juju-run', 'parameters': {'command': 'unit-get private-address', 'timeout': 300}}, 'enqueued': '2018-04-12T16:36:28Z', 'started': '0001-01-01T00:00:00Z', 'completed': '0001-01-01T00:00:00Z', 'status': 'pending'}]}}
RES: <juju.client._definitions.ActionResults object at 0x7fd9802f23c8>
ACTION: {'model-uuid': '1a035018-71ff-473e-8aab-d1a8d6b6cda7', 'id': '67eb94dc-f8a0-4333-878e-fbabf77862a5', 'receiver': 'ubuntu/0', 'name': 'juju-run', 'parameters': {'command': 'unit-get private-address', 'timeout': 300}, 'status': 'failed', 'message': 'command cancelled', 'enqueued': '2018-04-12T16:36:28Z', 'started': '2018-04-12T16:36:28Z', 'completed': '2018-04-12T16:36:28Z'}

I have tested with various timeout values including large ones in case it is in microseconds. But they all show failed immediately.

**Comment by gnuoy** [comment]
I'm guessing you didn't try nanoseconds because thats what the timeout value is looking for :-)
