### ISSUE TITLE
Model.wait_for_action should handle action already completed

### ISSUE THREAD

**Issue by johnsca** [juju/python-libjuju#245]
If [`Model.wait_for_action`](https://github.com/juju/python-libjuju/blob/master/juju/model.py#L867-L878) is called for an action that has already completed, it will block indefinitely.  If that's the case, it should handle it gracefully by returning immediately.  There may be some potential for a race condition here, so care should be taken to consider that.

If this is done, [`Model.get_action_output`](https://github.com/juju/python-libjuju/blob/master/juju/model.py#L1549-L1582) could be cleaned up to use it again.

**Comment by juanmanuel-tirado** [comment]
This issue has expired.
