### ISSUE TITLE
Increase charm store timeout from 5s

### ISSUE THREAD

**Issue by eggyal** [juju/python-libjuju#261]
**python-libjuju** currently sets a 5s timeout for calls to the charm store:

https://github.com/juju/python-libjuju/blob/514e47986c5b7875e9143ff4c46a212afacebd60/juju/model.py#L2165

Of course, failed attempts to access the store are retried after a 1s delay (up to three attempts in total):

https://github.com/juju/python-libjuju/blob/514e47986c5b7875e9143ff4c46a212afacebd60/juju/model.py#L2179-L2185

Unfortunately, if the store is responding slowly, all three attempts can easily fail (causing a deployment to error and abort).  A longer timeout would reduce the risk of such an annoying happenstance: I suggest 15s?

**Comment by johnsca** [comment]
Fixed in #262
