### ISSUE TITLE
libjuju does not manage the local model list cache

### ISSUE THREAD

**Issue by gnuoy** [juju/python-libjuju#267]
If a model is created using libjuju then the model cache file **~/.local/share/juju/models.yaml** is not updated with the model information. This means that juju command line commands targeted at the model fail with model not found errors. The cache can be updated with "juju list-models" or "juju switch".

Perhaps libjuju should be updated to add the model to the local cache?

```
$ cat /tmp/create-model.py 
#!/usr/bin/env python3


from juju import loop
from juju.controller import Controller

async def main():
    model_name = 'test'
    controller = Controller()
    await controller.connect()
    model = await controller.add_model(model_name)
    await model.connect()
    model_name = model.info.name
    await model.disconnect()
    await controller.disconnect()

if __name__ == '__main__':
    loop.run(main())

$ /tmp/create-model.py 

$ juju deploy -m test cs:ubuntu
ERROR model gnuoy-serverstack:admin/test not found

$ juju switch test
gnuoy-serverstack:admin/zaza -> gnuoy-serverstack:admin/test

$ juju deploy -m test cs:ubuntu
Located charm "cs:ubuntu-12".
Deploying charm "cs:ubuntu-12".```

**Comment by gnuoy** [comment]
Related bug https://bugs.launchpad.net/juju/+bug/1793303

**Comment by johnsca** [comment]
Seems reasonable to have it add to the file if it exists, but it should handle it gracefully if not, since it is a goal to have libjuju work without the CLI installed.  Also, I wonder if it would be worth adding some flag to `add_model` to disable this, if desired, though I can't really think why you would want to do that.

**Comment by dannf** [comment]
I'm confused about the status of this bug. It is still open, but https://github.com/openstack-charmers/zaza/pull/243 asserts that it is fixed (perhaps by https://github.com/juju/juju/pull/9403 ?) At any rate, we seem to be seeing this (still/again?) in our `juju`-based testing infrastructure. We have a libjuju script that creates a model and then we have a second script that runs tests against that model. Depending on the test, that could be another libjuju script, or a shell script using the CLI. When it is the CLI, we often see failures like `ERROR model jenkins:admin/scalebot-jenkins-checkbox-model-crb2s-focal-8 not found`, even though we can see that model does indeed exist upon post analysis. This is with `2.9.32-ubuntu-amd64`.

**Comment by juanmanuel-tirado** [comment]
Could you please confirm that this behaviour can be observed with version 3.0.4?
