### ISSUE TITLE
Bundle deploy fails with Juju 2.5-beta

### ISSUE THREAD

**Issue by johnsca** [juju/python-libjuju#272]
Originally reported at https://github.com/conjure-up/conjure-up/issues/1537

Apparently, this is due to the addition of support for bundles for Kubernetes models.

Some additional info from @wallyworld:

https://discourse.jujucharms.com/t/bundles-now-supported/365/2

There are 2 new AddApplication GUI args appended to the end of the current list:

- scale/num_units (int)
- placement (string)

These are used with the ApplicationDeploy params. For IAAS bundles we always
send numUnits=0 when making the deploy api call. For k8s, we need to pass in
that number.

The placement string is used to construct a single placement directive struct:

https://github.com/juju/juju/blob/develop/cmd/juju/application/bundle.go#L622

There's also a new ScaleApplication change event created when the user
re-deploys a k8s bundle with a scale change. It calls the ScaleApplication() API.

https://github.com/juju/juju/blob/develop/cmd/juju/application/bundle.go#L668

**Comment by aliouba** [comment]
It was related to the juju lib version (juju==0.10.2) and it is resolved after upgrading to 0.11.2.
