### ISSUE TITLE
Attaching resources is not implemented

### ISSUE THREAD

**Issue by aieri** [juju/python-libjuju#294]
the `attach()` function of class `juju.application.Application` is not implemented yet. This prevents charms that require resources from being deployed via libjuju.

**Comment by ajkavanagh** [comment]
+1

Yup, I need this too.  I'm looking in how to do it.

**Comment by cderici** [comment]
Let's move this to the front lines.

Also we should probably have a binding for `list-resources` (the implementation is in `get_resources`)

https://github.com/juju/python-libjuju/blob/a5ff4118ed63e5238951caf47c8dc170ba38ff69/juju/application.py#L436
