### ISSUE TITLE
unit.run doesn't honor timeout passed

### ISSUE THREAD

**Issue by auria** [juju/python-libjuju#300]
* juju 0.11.5
* I've seen https://github.com/juju/python-libjuju/commit/462989bbd919f209ebb7454305f53e4b94714487
* Term1: `juju run --timeout 900s --unit openstack-service-checks/0 'sleep 600; echo ok'`
* Term2: python3's `action = await unit.run(command, timeout)` where `timeout=5`

```
DEBUG:juju.client.connection:connection 140611577774208 <- {'request-id': 6, 'response': {'deltas': [['action', 'change', {'model-uuid': 'b4bd499a-6b00-44ce-80c2-ab1d9d01be5e', 'enqueued': '2019-04-11T15:59:36Z', 'name': 'juju-run', 'receiver': 'openstack-service-checks/0', 'id': 'ed0c416e-92c7-456c-820c-e8da1ac3d380', 'started': '0001-01-01T00:00:00Z', 'message': '', 'status': 'pending', 'parameters': {'command': '/bin/echo OK', 'timeout': 5000000000}, 'completed': '0001-01-01T00:00:00Z'}]]}}
```
timeout is 5s (in nanoseconds), but the following is shown and once Term1 command finishes, Term2 will return the expected output (no matter it should've timed out):
```
DEBUG:juju.client.connection:connection 140611588042592 -> {
  "request-id": 7,
  "request": "Ping",
  "params": {},
  "type": "Pinger",
  "version": 1
}
DEBUG:websockets.protocol:client > Frame(fin=True, opcode=1, data=b'{\n  "request-id": 7,\n  "request": "Ping",\n  "params": {},\n  "type": "Pinger",\n  "version": 1\n}', rsv1=False, rsv2=False, rsv3=False)
DEBUG:websockets.protocol:client < Frame(fin=True, opcode=1, data=b'{"request-id":7,"response":{}}\n', rsv1=False, rsv2=False, rsv3=False)
DEBUG:juju.client.connection:connection 140611588042592 <- {'request-id': 7, 'response': {}}
DEBUG:juju.client.connection:connection 140611577774208 -> {
  "request-id": 80,
  "request": "Ping",
  "params": {},
  "type": "Pinger",
  "version": 1
}
DEBUG:websockets.protocol:client > Frame(fin=True, opcode=1, data=b'{\n  "request-id": 80,\n  "request": "Ping",\n  "params": {},\n  "type": "Pinger",\n  "version": 1\n}', rsv1=False, rsv2=False, rsv3=False)
DEBUG:websockets.protocol:client < Frame(fin=True, opcode=1, data=b'{"request-id":80,"response":{}}\n', rsv1=False, rsv2=False, rsv3=False)
DEBUG:juju.client.connection:connection 140611577774208 <- {'request-id': 80, 'response': {}}
```

OTOH, app.run marks actions in status=pending but they don't complete. What am I doing wrong? Thank you.

**Comment by auria** [comment]
Juju controller version is 2.5.3

**Comment by johnsca** [comment]
`Unit.run()` is [documented](https://pythonlibjuju.readthedocs.io/en/latest/api/juju.unit.html#juju.unit.Unit.run) as accepting a timeout in seconds.  It [converts the timeout to nanoseconds](https://github.com/juju/python-libjuju/blob/master/juju/unit.py#L136-L138) before passing it to the API.

I think the common case would be to have timeouts on the order of seconds rather than nanoseconds, and you can pass in a decimal / fractional number to select smaller timeouts.

The log of the run command that you included has `{'command': '/bin/echo OK', 'timeout': 5000000000}` which doesn't include the sleep, but does include the timeout of 5s.  Can you please ensure that you include the sleep and have the timeout shorter than the sleep to confirm if the timeout on the order of seconds is honored?

**Comment by auria** [comment]
hey @johnsca, so this behavior is really interested. I knew about the seconds-to-nanoseconds conversion (which I referenced) and I now see that adding a longer sleep before the "echo" command, having a shorter timeout, works as you mention.

However, what is interesting is the difference between these two cases:
 * On both cases, leave `juju run --timeout 900s --unit openstack-service-checks/0 'sleep 600; echo ok'` on the background.
 * Case 1:
 ```
 juju run --timeout 10s --unit openstack-service-checks/0 'echo ok'                                                                                                
 ERROR timed out waiting for result from: unit openstack-service-checks/0
 ```
 * Case 2: `action = await unit.run(command, timeout)`, where `command=echo ok` and `timeout=5`

As you see in the first case, juju-run quits after 10 seconds, becase the `sleep 600` in the background blocked it. On the other hand, case 2 *waits* until the background command has finished (so, 10m in the example) and then runs the command. As you mention, if the command takes more than `timeout=5`, then it will fail (`action.status == 'failed' and action.message == 'command cancelled'`).

The expectation is that `unit.run` will raise an exception due to `timeout=5`, not hat it takes a maximum of 600+5 (in the example).

**Comment by cderici** [comment]
Closing for old age. Please re-open with the up to date details (versions etc) if this is still a problem.
