### ISSUE TITLE
Certificate Error while connecting to application

### ISSUE THREAD

**Issue by knkski** [juju/python-libjuju#302]
I've got an Ambassador instance that I've exposed like this:

    juju config kubeflow-ambassador juju-external-hostname=localhost
    juju expose kubeflow-ambassador

Previously that worked for me, however after refreshing on the edge channel of the juju snap, I get this error when attempting to connect to the instance:

```python
CertificateError("hostname '10.152.183.243' doesn't match either of 'anything', 'juju-apiserver', 'juju-mongodb', 'localhost'",)
```

I tried exposing Ambassador with an external hostname of the IP address and got the same error. @johnsca seemed to think it was related to https://github.com/juju/python-libjuju/pull/296, cc @howbazaar

**Comment by knkski** [comment]
This works after manually setting up the Ambassador instance's public IP as `juju-apiserver` in `/etc/hosts`, and connecting to `http://juju-apiserver/`.

**Comment by johnsca** [comment]
@howbazaar Would it make sense to include an option, possibly on by default, to skip validation of the host name?  It seems that if we're providing an explicit cert to validate against, the host name check is somewhat superfluous, but I'm not quite versed enough in TLS to know for sure if that is sufficiently secure.

**Comment by battlemidget** [comment]
https://github.com/juju/python-libjuju/issues/302

**Comment by johnsca** [comment]
From @alexmurray:

> on the surface of it that seems fine to me - if you have a pre-shared cert and you ensure you only trust this then as long as you ensure no-one else can get hold of this cert to impersonate the endpoint then I can't any obvious issues with this
> I agree with joe that hostname checking adds an extra layer of protection but since the hostname could be anything that probably is less relevant in this case
