### ISSUE TITLE
juju.application.Application.get_config returns charm config only

### ISSUE THREAD

**Issue by SimonRichardson** [juju/python-libjuju#314]
`Application.get_config` only returns the what Juju considers a CharmConfig(`config` part), which isn't ideal. Instead when calling `get_config` should return the serialised version of [`ApplicationGetResults`](https://github.com/juju/juju/blob/b3f223256bc12071fca2e24f8d97b4605b2b008c/apiserver/params/applications.go#L195-L204).

That should allow libjuju be congruent with Juju itself. This is a breaking change, alternatively we could consider just making a new method `get_app_config` or similar.

**Comment by mitechie** [comment]
Would it be a breaking change? It would be everything in the CharmConfig +
the app config additions?

**Comment by SimonRichardson** [comment]
Example:

```json
{
   "hostname":{
      "source":"unset",
      "type":"string",
      "description":"Override hostname of machine, when empty uses default machine hostname"
   }
}
```

Becomes (notice what the root node is):
```json
{  
   "config":{  
      "hostname":{  
         "type":"string",
         "description":"Override hostname of machine, when empty uses default machine hostname",
         "source":"unset"
      }
   },
   "constraints":null,
   "application":"ubuntu",
   "charm":"ubuntu",
   "series":"bionic"
}
```
