### ISSUE TITLE
Wishlist: Provide Public API for cross-model relations

### ISSUE THREAD

**Issue by afreiberger** [juju/python-libjuju#323]
There are internal APIs for AddApplicationOffer(s) that would be useful to have available in juju.model public API namespace in order to perform testing of cross-model relations for complex functional test requirements.

**Comment by mitechie** [comment]
These are coming as part of the work to add CMR support to bundles which is underway. Thanks for the request!

**Comment by mitechie** [comment]
This is now available in the 2.6 release and includes examples for using Cross Model Relations through the client library.
