### ISSUE TITLE
Need to log unit action activity without enabling DEBUG logging

### ISSUE THREAD

**Issue by ryan-beisner** [juju/python-libjuju#346]
There are certain activities which I need to log in OpenStack Charm testing, but they are set in libjuju at the DEBUG level.  The DEBUG level is hyper-verbose, with tons of Watcher and Pinger noise.  While that is helpful when triaging tricky issues, it prevents us from seeing some useful log messages because we can't enable DEBUG everywhere on all test runs due to the noise level.

I'm proposing to shift a number of log.debug() entries to a log.info() level to improve the general observability and UX.

**Comment by juanmanuel-tirado** [comment]
This was already fixed in #347
