### ISSUE TITLE
AddRelation() got an unexpected keyword argument 'via_cidrs'

### ISSUE THREAD

**Issue by matuskosut** [juju/python-libjuju#365]
When deploying a bundle with `libjuju 2.6.3 `and `juju 2.4.7` I got a TypeError with unexpected keyword argument 'via_cidrs'.

I noticed there were some changes regarding parameters in model.py https://github.com/juju/python-libjuju/commit/e8cc12c973841395e57782416fa0bffc0ee0f898:
```
-  result = await app_facade.AddRelation([relation1, relation2], None)
+ result = await app_facade.AddRelation(endpoints=[relation1, relation2], via_cidrs=None)
```

Which were followed in facades (https://github.com/juju/python-libjuju/commit/24c770717bfabd47c36dc1eb87d4d08db6ee4abf) with setting default values e.g. `via_cidrs=None`, but also adding `**kwargs` added, that would cover extra arguments even if method didn't support them.

This was later reconsidered (https://github.com/juju/python-libjuju/commit/17bbae0f6eeb62fa6a41a916634fd6b07e33dd9e), defaults were kept, but `**kwargs` were removed. So to summarize it, currently the definitions and calls look like this:

```
juju/model.py:            result = await app_facade.AddRelation(endpoints=endpoints, via_cidrs=None)
juju/client/_client4.py:    async def AddRelation(self, endpoints=None):
juju/client/_client9.py:    async def AddRelation(self, endpoints=None, via_cidrs=None):
juju/client/_client5.py:    async def AddRelation(self, endpoints=None):
juju/client/_client8.py:    async def AddRelation(self, endpoints=None, via_cidrs=None):
juju/client/_client3.py:    async def AddRelation(self, endpoints=None):
juju/client/_client2.py:    async def AddRelation(self, endpoints=None):
juju/client/_client10.py:    async def AddRelation(self, endpoints=None, via_cidrs=None):
juju/client/_definitions.py:class AddRelation(Type):
```

The question here is.. Is it necessary to use `app_facade.AddRelation(endpoints=endpoints, via_cidrs=None)` in model.py, therefore cause it incompatible with older facades? Or would it be all right to use `app_facade.AddRelation(endpoints=endpoints)` since all the definitions in client are assing via_cidrs to None by default anyway. Regarding that in model.py cidrs is None always.

**Comment by SimonRichardson** [comment]
That does seem like a bad compatibility issue, I would hope that we dropped the via_cidrs for APIs that didn't care.

**Comment by juanmanuel-tirado** [comment]
I consider this issue to be expired. Please re-open if it persists.
