### ISSUE TITLE
[Wishlist] Publish libjuju as a deb via Launchpad.

### ISSUE THREAD

**Issue by mskalka** [juju/python-libjuju#386]
For users behind a proxy or in other limited ingress situations pypi is typically blocked by whatever proxy or firewall managing that ingress. For this reason (among many others) many popular python API libraries are distributed via Launchpad.

**Comment by mitechie** [comment]
Is the library used in some other tool? I'd hate to get into a dep battle
over time and so Ideally if there was something like Zazza doing test
running, or another tool using the library they'd have it built into their
own work?

**Comment by mskalka** [comment]
I can't speak to the wider use of libjuju but generally it's on the user or distributor of a tool to manage their own dependency issues. Zaza certainly uses libjuju however it utilizes venvs so collisions are a non-issue.

**Comment by juanmanuel-tirado** [comment]
We have no plans for distributing python-libjuju as a deb via Launchpad in next roadmaps. Please reopen if further discussion is required.
