### ISSUE TITLE
"machine-status" missing in model.get_status caused KeyError for juju-lint

### ISSUE THREAD

**Issue by guoqiao** [juju/python-libjuju#387]
ouput from `model.get_status` doesn't have `machine-status` in it, while `juju status --format json` does. Using it for `juju-lint` will fail with `KeyError`: 
```
2020-01-22 07:28:59 [ERROR] OpenStack charm 'openstack-dashboard' not found
Traceback (most recent call last):
  File "/usr/bin/juju-lint", line 11, in <module>
    load_entry_point('juju-lint===1.0.0.dev2-201910310005-ubuntu18.04.1', 'console_scripts', 'juju-lint')()
  File "/usr/lib/python3/dist-packages/jujulint.py", line 453, in main
    lint(filename, lint_rules)
  File "/usr/lib/python3/dist-packages/jujulint.py", line 421, in lint
    check_statuses(j, applications)
  File "/usr/lib/python3/dist-packages/jujulint.py", line 340, in check_statuses
    check_status_pair(machine_name, "machine", juju_status["machines"][machine_name])
  File "/usr/lib/python3/dist-packages/jujulint.py", line 330, in check_status_pair
    check_status("%s %s" % (status_type.title(), name), data_d[primary],
KeyError: 'machine-status'
juju-lint failed with the following error: Command '['juju-lint', '--config', '/usr/share/juju-lint/contrib/canonical-openstack-rules.yaml', '--override-subordinate', '', '--loglevel', 'INFO', '--logfile', '', '/var/lib/juju-lint/juju-status.json']' returned non-zero exit status 1.

```

**Comment by guoqiao** [comment]
Just noticed `juju-status` is missing too.

**Comment by SimonRichardson** [comment]
Hi @guoqiao, is there any chance we can get a reproducer of this, that way we can expedite this bug.

Thanks.

**Comment by guoqiao** [comment]
Hi @SimonRichardson ,
To reproduce:
- prepare a juju env with some machines in it
- use `Model.get_status().to_json()` to generate a `juju-status.json`
- you can compare with output of `juju status --format json` to confirm that `machine-status` and `juju-status` is missing in above json
- get juju-lint: git clone https://git.launchpad.net/juju-lint
- run juju-lint: 
```
     cd juju-lint
     ./jujulint.py -c contrib/canonical-openstack-rules.yaml ~/charms/juju-status.json
```
Now you should see above KeyError message.

**Comment by juanmanuel-tirado** [comment]
I could see that machine-status is already in the `model.get_status()` function. Reopen if this issue persists.
