### ISSUE TITLE
Libjuju is not copying symlinks to folders

### ISSUE THREAD

**Issue by davigar15** [juju/python-libjuju#391]
This affects the symlink `lib/ops` for the new operator framework, that's not being copied.

**Comment by AdamIsrael** [comment]
To add some clarification:

Symlinks to folders aren't added to the Zipfile generated when deploying a local charm, in `model.py` in the `CharmArchiveGenerator` class.

**Comment by SimonRichardson** [comment]
Closing this as it's landed in master.
