### ISSUE TITLE
Race condition between app.set_config and model.block_until

### ISSUE THREAD

**Issue by auria** [juju/python-libjuju#408]
As part of a functional test, I have the following snippet:
```
await app.set_config({'param': value})
await model.block_until(lambda: app.units[0].agent_status == 'idle', timeout=600, wait_period=1)
```

It may happen that `model.block_until` matches the condition before the config change has actually reached the Juju controller. The expectation is that the agent_status would be in `executing` state and that no further instructions would be run until the change finishes completely.

One of our use cases changes a port in use by an application, which takes some time and skipping the block_until instruction would make the test fail.

An ugly workaround is to set `await asyncio.sleep(2)` in between the statements above. This may reduce false positives, although a really slow Juju controller would still make the tests fail.

What approach would you recommend to only wait the minimum as possible?

**Comment by matuskosut** [comment]
Have you tried block for app.get_config first? To see if it already returns the value as set, before moving on to agent_status? E.g.:
```
lambda: app.get_config()['param'] == value
```

**Comment by gnuoy** [comment]
On Fri, 1 May 2020 at 17:02, Alvaro Uría <notifications@github.com> wrote:

> As part of a functional test, I have the following snippet:
>
> await app.set_config({'param': value})
> await model.block_until(lambda: app.units[0].agent_status == 'idle', timeout=600, wait_period=1)
>
> It may happen that model.block_until matches the condition before the
> config change has actually reached the Juju controller. The expectation is
> that the agent_status would be in executing state and that no further
> instructions would be run until the change finishes completely.
>
> One of our use cases changes a port in use by an application, which takes
> some time and skipping the block_until instruction would make the test fail.
>
It's not perfect but you can check for executing before then checking for
idleness, there's an example here *1. If at all possible the best approach
is to check that the config set has done what you expect eg use something
like block_until_file_has_contents *2 and then wait for idleness.


*1
https://github.com/openstack-charmers/zaza-openstack-tests/blob/master/zaza/openstack/charm_tests/ceph/rbd_mirror/tests.py#L170-L180
*2
https://github.com/openstack-charmers/zaza/blob/master/zaza/model.py#L1207

**Comment by juanmanuel-tirado** [comment]
This issue seems to be expired. Reopen if required.
