### ISSUE TITLE
Handle local charms

### ISSUE THREAD

**Issue by johnsca** [juju/python-libjuju#41]
Local charms currently don't work either for single charm deploy nor in a bundle.  We'll need to pull in [this code](https://bazaar.launchpad.net/~juju-deployers/python-jujuclient/trunk/view/head:/jujuclient/environment.py#L120) from pythonclient.

For the bundle support, I think we'll also need to munge the bundle to change the charm paths to a format accepted by the API (currently gives an error like `charm path in application "topbeat" does not exist: /tmp/builds/topbeat`).

**Comment by tvansteenburgh** [comment]
Fixed by e89d5d4e03bb39c0dc5f0606f6f32b77e7d152b2
