### ISSUE TITLE
empty authtype not supported

### ISSUE THREAD

**Issue by wallyworld** [juju/python-libjuju#411]
Raised as a lp bug here https://bugs.launchpad.net/juju/+bug/1875632

Pasted info....

Hello,

I can't create a model with libjuju in an lxd-cloud added to a manual controller. With the juju client works fine, but I'm getting this error in libjuju: juju.errors.JujuAPIError: failed to create config: provider config preparation failed: validating cloud spec: "empty" auth-type not supported

Juju version: 2.7.6

How to setup the environment:
- VM with manual juju controller
- VMs with LXD cluster (it doesn't need to be several VMs, with 1 is enough)
- VM from where we will bootstrap the manual controller, add the LXD Cloud, etc.

lxd-cloud.yaml and lxd-credentials.yaml: https://pastebin.canonical.com/p/ghG62DfNG9/

With the juju client it works:https://pastebin.canonical.com/p/wCvVgk5n6m/

With libjuju it doesn't: https://pastebin.canonical.com/p/3WhzF5jh6Y/
Script for libjuju: https://pastebin.canonical.com/p/V8MwKrzJZV/

---

So I can replicate this, essentially pylibjuju doesn't check the controller (cloudapi) for any controller credentials like what juju add-model does[1]. So you need to specify a credential_name of admin when you use add_model.

1. https://github.com/juju/juju/blob/develop/cmd/juju/controller/addmodel.go#L494-L519

**Comment by SimonRichardson** [comment]
Fixed this with the author of the bug. @wallyworld can you close the bug in launchpad for me.
