### ISSUE TITLE
*** TypeError: 'ActionSpec' object is not subscriptable

### ISSUE THREAD

**Issue by davigar15** [juju/python-libjuju#417]
*** TypeError: 'ActionSpec' object is not subscriptable

I'm getting that error in the function application.get_actions()

**Comment by hpidcock** [comment]
See #413 #414 We are hoping to have a new release out tomorrow. For now either use juju-2.7.1 or https://github.com/juju/python-libjuju/tarball/master#egg=juju-2.8.0

**Comment by battlemidget** [comment]
Please note https://github.com/juju/python-libjuju/pull/415 has surfaced several issues including this one.
