### ISSUE TITLE
Unknown delta type: id 

### ISSUE THREAD

**Issue by afreiberger** [juju/python-libjuju#450]
During zaza testing, inside of a model.block_until() loop, we're seeing the following happening on juju 2.8.5 models.

[WARNING] Unknown delta type: id

It appears the exception is coming from Model._watch():
https://github.com/juju/python-libjuju/blob/133433a910e5d62de8959c3ffed5736598b05c1f/juju/model.py#L905

And that the list of known delta types is listed here:
https://github.com/juju/python-libjuju/blob/9e31ce1e79c9954ef226cb3076de66ddaafcb3ee/juju/delta.py#L109

This is causing very large logs during functional testing of openstack and openstack related charms utilizing the juju/zaza model block_until*() functions.

Opened bug on LP to track:
https://bugs.launchpad.net/juju/+bug/1900626

**Comment by SimonRichardson** [comment]
The fix is to handle all delta types. Can you paste the ones you're seeing, which will help prioritize.

**Comment by afreiberger** [comment]
Sorry, it's in the subject line and in the lp bug, but the only one we're seeing repeatedly is: "id"

[WARNING] Unknown delta type: id

**Comment by SimonRichardson** [comment]
That is indeed very unhelpful.

**Comment by afreiberger** [comment]
To replicate:

charm pull elasticsearch
cd elasticsearch
make submodules
make functional

**Comment by SimonRichardson** [comment]
This has been fixed with #451
