### ISSUE TITLE
Refactor loop arguments for asyncio calls

### ISSUE THREAD

**Issue by SimonRichardson** [juju/python-libjuju#461]
> DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.

At some point, pylibjuju will stop working with the latest 3.x Python. We should fix pylibjuju to remove the loop argument and be done with it. This doesn't look like a massive task, but it does have consequences, in that we can only support 3.5.3, 3.6, 3.7 and onwards, but that might be more difficult because of our support program.

**Comment by cderici** [comment]
Closing, per https://github.com/juju/python-libjuju/pull/560 and https://github.com/juju/python-libjuju/pull/580 .
