### ISSUE TITLE
Drop support for python 3.5

### ISSUE THREAD

**Issue by SimonRichardson** [juju/python-libjuju#468]
> DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.

It should be noted that Python 3.5 is EOL.

**Comment by juanmanuel-tirado** [comment]
Support was already dropped.
