### ISSUE TITLE
machine.hostname has no data with Juju 2.8.10+

### ISSUE THREAD

**Issue by xavpaice** [juju/python-libjuju#476]
Prior to PR #475, if I have a Unit object named 'unit':

(Pdb) unit.machine.hostname
*** KeyError: 'hostname'

With this change the attribute is there, but not populated with data:

(Pdb) unit.machine.hostname
(Pdb)
(Pdb) self.model.machines['0'].hostname
(Pdb) 

However, juju show-machine does show the hostname clearly as this is a new model, running 2.8.10 from edge.

Is there some schema update needed in addition to the new property in machine.py?

**Comment by xavpaice** [comment]
bit more info if it's helpful:

```> /home/xav/repos/juju-verify/.tox/func/lib/python3.8/site-packages/juju/machine.py(333)hostname()
-> if 'hostname' in self.safe_data and self.safe_data['hostname'] != '':
(Pdb) self.safe_data
{'model-uuid': '3c9e76f4-f083-456e-8ad5-36ce22e2f79a', 'id': '0', 'instance-id': 'd68d1603-bacd-42f0-bb8d-9ffe0a107f94', 'agent-status': {'current': 'started', 'message': '', 'since': '2021-03-14T20:45:33.966549218Z', 'version': '2.8.10'}, 'instance-status': {'current': 'running', 'message': 'ACTIVE', 'since': '2021-03-14T20:44:21.763972231Z', 'version': ''}, 'life': 'alive', 'series': 'xenial', 'container-type': '', 'supported-containers': ['lxd', 'kvm'], 'supported-containers-known': True, 'hardware-characteristics': {'arch': 'amd64', 'mem': 2048, 'root-disk': 20480, 'cpu-cores': 1, 'availability-zone': 'nova'}, 'jobs': ['JobHostUnits'], 'addresses': [{'value': '10.5.0.4', 'type': 'ipv4', 'scope': 'local-cloud'}, {'value': '252.0.4.1', 'type': 'ipv4', 'scope': 'local-fan'}, {'value': '127.0.0.1', 'type': 'ipv4', 'scope': 'local-machine'}, {'value': '::1', 'type': 'ipv6', 'scope': 'local-machine'}], 'has-vote': False, 'wants-vote': False}

(Pdb) self.data
{'model-uuid': '3c9e76f4-f083-456e-8ad5-36ce22e2f79a', 'id': '0', 'instance-id': 'd68d1603-bacd-42f0-bb8d-9ffe0a107f94', 'agent-status': {'current': 'started', 'message': '', 'since': '2021-03-14T20:45:33.966549218Z', 'version': '2.8.10'}, 'instance-status': {'current': 'running', 'message': 'ACTIVE', 'since': '2021-03-14T20:44:21.763972231Z', 'version': ''}, 'life': 'alive', 'series': 'xenial', 'container-type': '', 'supported-containers': ['lxd', 'kvm'], 'supported-containers-known': True, 'hardware-characteristics': {'arch': 'amd64', 'mem': 2048, 'root-disk': 20480, 'cpu-cores': 1, 'availability-zone': 'nova'}, 'jobs': ['JobHostUnits'], 'addresses': [{'value': '10.5.0.4', 'type': 'ipv4', 'scope': 'local-cloud'}, {'value': '252.0.4.1', 'type': 'ipv4', 'scope': 'local-fan'}, {'value': '127.0.0.1', 'type': 'ipv4', 'scope': 'local-machine'}, {'value': '::1', 'type': 'ipv6', 'scope': 'local-machine'}], 'has-vote': False, 'wants-vote': False}
(Pdb) self.entity_id
'0'
(Pdb) self.entity_type
'machine'

(Pdb) self.model.state.entity_history('machine', '0')
deque([{'model-uuid': '3c9e76f4-f083-456e-8ad5-36ce22e2f79a', 'id': '0', 'instance-id': 'd68d1603-bacd-42f0-bb8d-9ffe0a107f94', 'agent-status': {'current': 'started', 'message': '', 'since': '2021-03-14T20:45:33.966549218Z', 'version': '2.8.10'}, 'instance-status': {'current': 'running', 'message': 'ACTIVE', 'since': '2021-03-14T20:44:21.763972231Z', 'version': ''}, 'life': 'alive', 'series': 'xenial', 'container-type': '', 'supported-containers': ['lxd', 'kvm'], 'supported-containers-known': True, 'hardware-characteristics': {'arch': 'amd64', 'mem': 2048, 'root-disk': 20480, 'cpu-cores': 1, 'availability-zone': 'nova'}, 'jobs': ['JobHostUnits'], 'addresses': [{'value': '10.5.0.4', 'type': 'ipv4', 'scope': 'local-cloud'}, {'value': '252.0.4.1', 'type': 'ipv4', 'scope': 'local-fan'}, {'value': '127.0.0.1', 'type': 'ipv4', 'scope': 'local-machine'}, {'value': '::1', 'type': 'ipv6', 'scope': 'local-machine'}], 'has-vote': False, 'wants-vote': False}])
```

I suspect we need to add the new schema to client/schemas-juju-2.8.10.json and re-run facade.py in order to get the new property added.

**Comment by achilleasa** [comment]
Can you try the hostname example in the examples folder and let me know if that works for you (that one effectively polls until the agent starts)? 

Also you need to make sure you are running the edge snap with sha (0b54e0e5eff36c9de613c076703f70dfd193c876)[https://github.com/juju/juju/commit/0b54e0e5eff36c9de613c076703f70dfd193c876] or newer.

Note that the host name will only get populated **after** the machine agent dials in so before that (even though the machine is started), hostname will return None.

**Comment by xavpaice** [comment]
With the example, and my own tests using very similar code, I get:

`machine1 hostname: None`

With the CLI I'm able to read the hostname of the machine, so I'm confident that the 2.8.10 edge snap I'm using is OK.  I've got a venv built using the client installed with `pip install -e git+https://github.com/juju/python-libjuju.git#egg=juju`, and the machine status is always 'started' with units 'active' and 'idle'.

**Comment by xavpaice** [comment]
I am supposing you are able to see a hostname when I am not - is this because I'm using the openstack provider?

`(Pdb) machine1.hostname
(Pdb) machine1.agent_status
'started'
(Pdb) machine1.status_message
'ACTIVE'
(Pdb) machine1.safe_data
{'model-uuid': 'ab5d1e1b-14b3-422f-8c86-6049f3bac5ca', 'id': '7', 'instance-id': '38fe08f5-bbf6-4914-96eb-ac08c66adf96', 'agent-status': {'current': 'started', 'message': '', 'since': '2021-03-23T03:25:13.789202438Z', 'version': '2.8.10'}, 'instance-status': {'current': 'running', 'message': 'ACTIVE', 'since': '2021-03-23T03:23:49.8439857Z', 'version': ''}, 'life': 'alive', 'series': 'xenial', 'container-type': '', 'supported-containers': ['lxd', 'kvm'], 'supported-containers-known': True, 'hardware-characteristics': {'arch': 'amd64', 'mem': 2048, 'root-disk': 20480, 'cpu-cores': 1, 'availability-zone': 'nova'}, 'jobs': ['JobHostUnits'], 'addresses': [{'value': '10.5.0.17', 'type': 'ipv4', 'scope': 'local-cloud'}, {'value': '252.0.17.1', 'type': 'ipv4', 'scope': 'local-fan'}, {'value': '127.0.0.1', 'type': 'ipv4', 'scope': 'local-machine'}, {'value': '::1', 'type': 'ipv6', 'scope': 'local-machine'}], 'has-vote': False, 'wants-vote': False}
`

**Comment by achilleasa** [comment]
@xavpaice The reason I am asking to double-check the sha you are running is that this change particular landed in two PRs. The first PR adds the hostname reporting + displaying it in `juju show-machine` (I believe you are running the code from this PR) and the _latter_ adds the hostname to the set of data reported by the allwatcher facade (this change is required to make the hostname field visible to pylibjuju).

If you try to bootstrap with the current 2.8/edge snap you should get this information via pylibjuju as well. Let me know if this doesn't work for you and I will investigate further.

**Comment by SimonRichardson** [comment]
2.8.6 has been released to [PyPi](https://pypi.org/project/juju/)

**Comment by xavpaice** [comment]
I bootstrapped a fresh controller from snap 2.8.10-341884e (re-installed immediately before), and re-ran the tests - all good this time round.  I guess I had bootstrapped the controller with a slightly older snap after all, and the upgrade from 2.8.10 to 2.8.10 is a bit harder than just a normal release version upgrade.

Thanks for the help!
