### ISSUE TITLE
Add support for fetching and discharging new macaroons

### ISSUE THREAD

**Issue by tvansteenburgh** [juju/python-libjuju#50]
The library currently has no support for doing this. You can use macaroon auth, but you must already possess valid macaroons for the controller or model you are connecting to. In practice this usually means you have connected with the juju cli, which gives you valid macaroons in ~/.go-cookies.

This was a good quick-and-dirty first start for enabling libjuju to connect to shared controllers, but it's not a long term solution and the pain of this approach is already being felt. It's important that we implement proper macaroon support asap.

**Comment by battlemidget** [comment]
@arosales Can we move this to a high priority? I want to make sure we have a plan of attack next week for getting this implemented asap

**Comment by jamesbeedy** [comment]
@tvansteenburgh any status updates on this?

**Comment by tvansteenburgh** [comment]
@jamesbeedy I'm afraid it's currently in "everyone knows it's important but no one has time" status. :(

**Comment by tvansteenburgh** [comment]
@jamesbeedy Yeah it's just libjuju. The library needs to grow the ability to fetch and discharge a new macaroon.

**Comment by battlemidget** [comment]
Well there is also the bakery aspect of it too right?

**Comment by jamesbeedy** [comment]
@tvansteenburgh @battlemidget from my understanding, the macaroon has to obtain (and contain) the openid token from ubuntu SSO right? How can this process be automated such that libjuju could request a macaroon without having the user manually have auth against Ubuntu SSO to get the token?

**Comment by tvansteenburgh** [comment]
@jamesbeedy AFAIK it can't. The lib will need to provide a way for a token to be passed in.

**Comment by jamesbeedy** [comment]
@tvansteenburgh do you have any insight as to how a token could be obtained on demand?

**Comment by juanmanuel-tirado** [comment]
This issue is five years old.
