### ISSUE TITLE
The output structure of Model.get_status is not consistent with `juju status --format=yaml`

### ISSUE THREAD

**Issue by jguedez** [juju/python-libjuju#500]
The output of `Model.get_status()` has a structure that is different from the structure provided by the juju client for the same data, mostly the keys are named differently, which causes confusion - it would be better for it to be consistent. This also forces tooling that consumes the information to be able to handle the differences which is not ideal.

These are the differences I have identified so far:

|      instance      |          jsfy           |       libjuju        |
|--------------------|-------------------------|----------------------|
| machine/container  | machine-status          | instance-status      |
| unit/subordinate   | workload-status         | workload-status      |
| application        | application-status      | status               |
| juju status msg    | workload-status.message | workload-status.info |
| juju agent details | (unit).juju-status      | (unit).agent-status  |

## example outputs
jsfy - https://pastebin.ubuntu.com/p/VZp6zjh7sw/
libjuju - https://pastebin.ubuntu.com/p/b7SjYK9WKX/

**Comment by SimonRichardson** [comment]
Can you make a bug at https://bugs.launchpad.net/juju/+bugs? 

This seems like consistency at a project level.

----

The reason it is inconsistent is that libjuju and juju call different APIs and the naming between each varies.

**Comment by jguedez** [comment]
@SimonRichardson Thanks, done - https://bugs.launchpad.net/juju/+bug/1930184

Let me know if you need more information.

**Comment by ajkavanagh** [comment]
Just a quick note: if you do end up changing the libjuju one's, will it be possible to at least retain the old keys for a while (with deprecation notices).  Zaza uses those quite extensively, and we'd break overnight (or have to pin back).  Thanks.
