### ISSUE TITLE
(Kubernetes) Closing controller connection breaks new model connection

### ISSUE THREAD

**Issue by johnsca** [juju/python-libjuju#505]
With the latest release, we're hitting an issue where adding a model to a K8s controller and then closing the controller connection (but not the model connection) causes the model connection to die.  Oddly, even trying to manually disconnect & reconnect the model also fails.  Reproduction case:

```python
import asyncio
import random
from juju.controller import Controller


async def test():
    controller = Controller()
    await controller.connect()
    nonce = "".join(random.choices("0123456789abcdef", k=4))
    model_name = f"test-model-{nonce}"
    model = await controller.add_model(model_name)
    model_uuid = model.info.uuid

    try:
        # This breaks the model connection
        await controller.disconnect()

        # This still fails
        connect_params = model.connection().connect_params()
        await model.disconnect()
        await model.connect(**connect_params)

        await model.get_config()
        await model.disconnect()

    finally:
        await controller.connect()
        await controller.destroy_model(model_uuid)
        await controller.disconnect()


if __name__ == '__main__':
    asyncio.run(test())
```

As is, the error is:

```
kubernetes.client.exceptions.ApiException: (0)
Reason: [Errno 2] No such file or directory
```

You also get this error if you comment out the controller disconnect but leave in the manual model reconnect.

If you only comment out the model reconnection, then the error is:

```
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason
```

If you comment out both, it will succeed.

**Comment by SimonRichardson** [comment]
From RFC6455

> If _The WebSocket
   Connection is Closed_ and no Close control frame was received by the
   endpoint (such as could occur if the underlying transport connection
   is lost), _The WebSocket Connection Close Code_ is considered to be
   1006.

So is Juju not even a closed frame on the websocket connection? This would seem like a bug in the underlying webscoket library. 

Relates to #604
