### ISSUE TITLE
workload status is reported as 'active' when container is starting and is 'waiting' in juju status

### ISSUE THREAD

**Issue by VariableDeclared** [juju/python-libjuju#515]
Hi,

Some workloads create resources on startup of the container as such waiting is required in order to test a charm. Currently the pylibjuju library is reporting 'active' whilst juju status is reporting 'waiting'. This causes an issue when using this metric to wait as the logic will continue and fail a test.

To Reproduce:
1. Create a container charm with the operator framework
2. attempt to get workload status from ops_test.model.applications['gatekeeper'].units[0].workload_status
3. Observe the container is still "waiting" on juju status

Thanks,

Peter

**Comment by SimonRichardson** [comment]
Essentially you need to derive the status as seen here https://github.com/juju/python-libjuju/blob/1c391f1a375368b292b91318ec019ab21823cc6d/juju/application.py#L83
