### ISSUE TITLE
python-libjuju does not implement model.create_backup

### ISSUE THREAD

**Issue by zzehring** [juju/python-libjuju#528]
Working on a juju tool for backups and found that python-libjuju does not provide functionality for model backups (particularly backing up the controller). Ideally, I'd want `juju create-backup` command functionality.

https://github.com/juju/python-libjuju/blob/8a037110bede2bc40e95d7096ce1cc19c66c429b/juju/model.py#L1313-L1321

**Comment by cderici** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) ['backup' functionality on Pylibjuju](https://trello.com/c/KHurboqp/3936-backup-functionality-on-pylibjuju)
