### ISSUE TITLE
python-libjuju does not implement juju.get_controllers

### ISSUE THREAD

**Issue by zzehring** [juju/python-libjuju#529]
https://github.com/juju/python-libjuju/blob/8a037110bede2bc40e95d7096ce1cc19c66c429b/juju/juju.py#L58-L63

**Comment by cderici** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [implement juju.py functions like juju.get_controllers](https://trello.com/c/m8BvbBi3/3952-implement-jujupy-functions-like-jujugetcontrollers)
