### ISSUE TITLE
"JujuConnectionError: Model not found" occurs when model exists but is not present in models.yaml

### ISSUE THREAD

**Issue by zzehring** [juju/python-libjuju#530]
When creating a new model, connecting to the new model fails as the local `~/.local/share/juju/models.yaml` is not updated with the new model until the model is acted upon (e.g. `juju models`, deploying something to the model via libjuju, etc). The model shows when running `list_models()` on a connected controller.

E.x:

```python3
from juju.controller import Controller
from juju.loop import run
from juju.model import Model

controller = Controller()
# a local lxd controller
run(controller.connect_current())

model_name = "my-model"
run(controller.add_model(model_name))

model = Model()
run(model.connect(model_name=model_name))
# this will raise "JujuConnectionError('Model not found: admin/my-model")"
```

Ideally, connecting to the model should be possible even though the model is not yet in the models.yaml cache, since the model does exist (and is present in `Controller.list_models()`).

And here's the bit that does the checking for model name and raising of exception.

https://github.com/juju/python-libjuju/blob/8a037110bede2bc40e95d7096ce1cc19c66c429b/juju/client/connector.py#L126-L130

Currently, I'm working around this by connecting to the model through the connected controller instance (`Controller.get_model(model_name)`).

**Comment by cderici** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [connect to an unsynced model -- issue 530](https://trello.com/c/BKKbIJU6/3943-connect-to-an-unsynced-model-issue-530)

**Comment by zzehring** [comment]
Thanks!
