### ISSUE TITLE
A blocking test case is causing the whole test build to time out

### ISSUE THREAD

**Issue by cderici** [juju/python-libjuju#534]
There's at most two test cases that seem to be blocking the test builds to complete, so the build times out after 120 minues. Here's an example console output from [such a build](https://jenkins.juju.canonical.com/job/github-integration-tests-pylibjuju-python3.7/86/console) :

![image](https://user-images.githubusercontent.com/120652/132371673-655dc690-738a-4ade-b866-35d6636cee3c.png)

Note that, because of this time out, `tox` can't get any chance to print any stderr output from any of the failing test cases. (which was the first symptom that lead us to this issue in the first place)

This seems to be related to test cases `test_macaroon_auth_with_bad_key` and `test_macaroon_auth_with_unauthorized_user`, as they are the only ones that were initiated but never finished with a line such as `PASSED` or `FAILED`. They both use the environment variable `TEST_AGENTS`, **disabling which allows the build to complete without a timeout**, because pytest skips them: 

![image](https://user-images.githubusercontent.com/120652/132372553-41f4a1ff-363a-4907-8140-39ade9303972.png)

No other test cases seem to depend on this environment variable. 

Running both cases on local with `TEST_AGENTS` defined as in the CI build (just grep for it on the console output) results in `juju.errors.JujuAPIError: no credentials provided` and completes just fine, since both tests are marked as `xfail`.

It is unclear why these cases block on CI.

**Comment by jameinel** [comment]
If they are marked X Fail I feel like they should just be removed. It was
someone thinking it should work in the future. But clearly wasn't
implemented.

**Comment by cderici** [comment]
These tests seem to come from [this commit](https://github.com/juju/python-libjuju/commit/37a7500245ae61fc2c103d1728a65b99485a9ef4) from several years ago. The author also adds in the end of the description:

![image](https://user-images.githubusercontent.com/120652/132764894-09d9b285-d69f-4989-8e0e-1389fcc16323.png)

Although it might be useful to revise these tests, it's not clear to me if they are fundamentally difficult run (mostly because I have only a very little idea about macaroons), but I'd be happy to remove them too, as they seem to have been born with `xfail` in the first place. Any ideas @SimonRichardson ?

**Comment by juanmanuel-tirado** [comment]
As rule of thumb those tests that are not well understood should be removed/commented. In this case, I would skip them and comment why the are ignored.

**Comment by cderici** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [skip the macaroon_auth tests](https://trello.com/c/SRIfwOnT/3951-skip-the-macaroonauth-tests)
