### ISSUE TITLE
python-libjuju does not implement model.download_backup

### ISSUE THREAD

**Issue by zzehring** [juju/python-libjuju#553]
Thanks to https://github.com/juju/python-libjuju/issues/528, we can create backups using libjuju. However, to pull down the backup, we need to pull down the backup archive manually (which requires changing file/directory permissions and `scp`ing the file). It would be awesome if this was built into libjuju.

https://github.com/juju/python-libjuju/blob/3d54f75dd74691fe8ecfaf614df8650b21b332b9/juju/model.py#L1928-L1935

**Comment by cderici** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [implement model.download_backup](https://trello.com/c/sFbXMJhu/4019-implement-modeldownloadbackup)
