### ISSUE TITLE
Model.add_machine is an attractive nuisance

### ISSUE THREAD

**Issue by abentley** [juju/python-libjuju#57]
add_machine is documented as if it does something, but it does nothing.  The fact that it exists and is documented is an attractive nuisance, because it leads people to try to use it.

Would-be users will eventually discover that its implementation is "pass", but it should be easier to know that it's not implemented.

Some alternatives:
* it could be deleted until it is implemented.
* it could raise NotImplementedError

**Comment by johnsca** [comment]
This was actually just merged an hour ago in #56.  I'm +1 to changing this to find any other `pass`es to `NotImplementedError`s, or open a separate issue for that.

**Comment by tvansteenburgh** [comment]
The implementation for this was just merged, so I'll close this, but for the record...

You make a good point. The library began as a big bunch of stubs that would simply "pass". It was a good way to define the structure and future api of the library. But you are right, raising NotImplementedError would be a better choice to avoid confusion.

I'll take some time to make that change soon, thanks for the suggestion. I'll open another issue accordingly.
