### ISSUE TITLE
wait_for_idle ignores idle_period if app has no units

### ISSUE THREAD

**Issue by sed-i** [juju/python-libjuju#574]
If an app has no units, then `wait_for_idle` would not wait `idle_period` before returning.
This may also be a problem when the host is slow enough (e.g. github actions) such that python-libjuju sees an app status of "active-idle" before a unit is started.

https://github.com/juju/python-libjuju/blob/c68ee681995dc4b966ed14160d61a72f249c3b7b/juju/model.py#L2624

**Comment by balbirthomas** [comment]
This issue may also benefit from a clarification on the semantics of the wait for idle method. In particular which of the two alternatives aligns with the intended semantics of this function
1. If `wait_for_idle(app=<some-app>, status=<some-status>)` is designed to only wait for `<some-app>` to reach status = `<some-status>`
OR
2. If `wait_for_idle(app=<some-app>, status=<some-status>)` guarantees that it will check if `<some-app>` has reached `<some-status>` **after** all the currently deployed units of `<some-app>` have become available.

**Comment by cderici** [comment]
> This issue may also benefit from a clarification on the semantics of the wait for idle method. In particular which of the two alternatives aligns with the intended semantics of this function
> 
>     1. If `wait_for_idle(app=<some-app>, status=<some-status>)` is designed to only wait for `<some-app>` to reach status = `<some-status>`
>        OR
> 
>     2. If `wait_for_idle(app=<some-app>, status=<some-status>)` guarantees that it will check if `<some-app>` has reached `<some-status>` **after** all the currently deployed units of `<some-app>` have become available.

This is true. Currently `wait_for_idle`'s behavior is unspecified if there's not any units, it'll just return (if not `raise_on...`).

The `idle_period` parameter is for saying "ok this unit has just switched into an `idle` state, let's see if it'll be in there for `idle_period` seconds, just to make sure it is actually idle". It doesn't indicate anything if there's not any units to track.

I think in case of no units it's reasonable to wait until any units show up, or we reach a timeout (which currently defaults to 600 seconds, should be more than enough). 

(Unless there's another way that I don't know for an application to be in an idle state without having any units. In that case `wait_for_idle` should try to check that -- potentially while waiting for units to show up) 

@SimonRichardson any thoughts?

**Comment by cderici** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [wait_for_idle's behavior when no units in app](https://trello.com/c/gtx0Nmfy/4140-waitforidles-behavior-when-no-units-in-app)

**Comment by ajkavanagh** [comment]
We have a similar function in zaza to wait for a model with application states that allows certain applications to have 0 expected units.  See https://github.com/openstack-charmers/zaza/blob/39ee47cf683eb45b98fbab7d2daa2f03b6d54f5d/zaza/model.py#L1239 if you want to crib the feature.
