### ISSUE TITLE
Repeated `asyncio` errors

### ISSUE THREAD

**Issue by jnsgruk** [juju/python-libjuju#576]
I've been using `pylibjuju` through the `pytest-operator` for testing, and I'm seeing this error *a lot*:

```
ERROR    asyncio:base_events.py:1738 Task exception was never retrieved
future: <Task finished name='Task-30' coro=<Connection._pinger() done, defined at /home/jon/code/canonical/operator-libs-linux/.tox/integration/lib/python3.9/site-packages/juju/client/connection.py:502> exception=Exception('No facade Pinger in facades {}')>
Traceback (most recent call last):
  File "/home/jon/code/canonical/operator-libs-linux/.tox/integration/lib/python3.9/site-packages/juju/client/connection.py", line 516, in _pinger
    pinger_facade = client.PingerFacade.from_connection(self)
  File "/home/jon/code/canonical/operator-libs-linux/.tox/integration/lib/python3.9/site-packages/juju/client/_client.py", line 65, in from_connection
    raise Exception('No facade {} in facades {}'.format(facade_name,
Exception: No facade Pinger in facades {}
```

and

```
ERROR    asyncio:base_events.py:1738 Task exception was never retrieved
future: <Task finished name='Task-402' coro=<WebSocketCommonProtocol.recv() done, defined at /home/jon/code/canonical/operator-libs-linux/.tox/integration/lib/python3.9/site-packages/websockets/protocol.py:443> exception=ConnectionClosedOK('code = 1000 (OK), no reason')>
Traceback (most recent call last):
  File "/home/jon/code/canonical/operator-libs-linux/.tox/integration/lib/python3.9/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/jon/code/canonical/operator-libs-linux/.tox/integration/lib/python3.9/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: code = 1000 (OK), no reason
```

These occur consistently on every run. More examples can be found here: https://github.com/jnsgruk/charm-kubernetes-dashboard/runs/4069754517?check_suite_focus=true#step:4:256

**Comment by SimonRichardson** [comment]
We should always have a Pinger facade. So either we're not connected any longer or we're attempting to create a Pinger without first building the facades. There are couple of locations that I think need investigation:

1. This will override the pinger and not close the old one. We should at least guard against that. https://github.com/juju/python-libjuju/blob/master/juju/client/connection.py#L802-L803
2. Reconnect doesn't rebuild the facades, it should https://github.com/juju/python-libjuju/blob/master/juju/client/connection.py#L684-L697
3. When tailing the debug-log we should ensure that we build the facades or disable the pinger functionality https://github.com/juju/python-libjuju/blob/master/juju/client/connection.py#L327
