### ISSUE TITLE
No Method to Create a Model

### ISSUE THREAD

**Issue by sfeole** [juju/python-libjuju#6]
Looking at the Class Model() 

It appears that we have the ability to connect to an existing Model.  Deploy a Unit and Run an Action. 

It would be nice to have the ability to Create a New Model ,  Deploy a Unit and Run Actions in there.  I see that the module juju/controller.py has this method stubbed out.

**Comment by tvansteenburgh** [comment]
Fixed by 6f9041acecc03eaf12a6c8e5d50d20d17a28e87f
