### ISSUE TITLE
 Juju.register() not implemented

### ISSUE THREAD

**Issue by mullumaus** [juju/python-libjuju#628]
Hi

Our charms use the authentication information taken from the data files created by juju register user. But  Juju.register() currently is not implemented. To avoid a mix usage of Juju CLI and python libjuju, can you  implement the Juju.register() function please?

https://github.com/juju/python-libjuju/blob/0f4e1a7b03ee2dc80afa2ceb0115f4960e96b8ab/juju/juju.py#L63

**Comment by cderici** [comment]
Hi Linda,

This is a change we %100 want as well. And initially it looks quite simple if we only think about the local use. However, to make it work the right way for everyone (where pylibjuju doesn't deal with any filesystem etc), the way that the pylibjuju works with the juju api needs to be revisited. 

Right now we're having architecture discussions of next steps of pylibjuju and how to make it simpler and lighter for every use. After the changes we're discussing on the architecture, having `juju register` will be very easy and natural. So we think this change is suitable for pylibjuju `3.0`, which hopefully will happen relatively soon.

For these reasons we're closing this issue without a resolution for now, however, this is certainly something we'll have in pylibjuju (working the right way for every use). Thanks for bringing it up!
