### ISSUE TITLE
FeatureRequest: add method for show_credential() 

### ISSUE THREAD

**Issue by jamesbeedy** [juju/python-libjuju#641]
Hello,

We feel like the pylibjuju api is missing a method `show_credential(cloud, credential_name)`.

How do others feel about adding this method to the api?

Thanks

**Comment by juanmanuel-tirado** [comment]
There is a general misconception of how `python-libjuju` works. `python-libjuju` is not a clone of `juju-cli`, it is a client to the `juju` interface. Credentials live outside the scope of the juju API, therefore they must not be manipulated by `python-libjuju`. This also applies to #640 

In this sense, we will keep away from offering functions that are not directly related with the juju API.
