### ISSUE TITLE
Need means of retrieving ingress addresses per unit

### ISSUE THREAD

**Issue by mmanciop** [juju/python-libjuju#644]
When using libjuju for writing integration tests for sidecar charms, there seems to be no ergonomic way of retrieving the ingress address (i.e., the unit pod ip) through libjuju. Ideally, we would have something like the [`public_address`](https://github.com/juju/python-libjuju/blob/1f50f544c9753d867ac33cf05543cf9002f1cf03/juju/unit.py#L69) property (which, btw, seems to always return `None` with sidecar charms).

**Comment by cderici** [comment]
@mmanciop Sorry for the delayed response, did you try to use the `unit.get_public_address()`? https://github.com/juju/python-libjuju/blob/e8456e118f1f2e494af9d885001063277e7cdfd1/juju/unit.py#L92

**Comment by cderici** [comment]
Closing this as incomplete (non-reproducible), feel free to re-open if needed.
