### ISSUE TITLE
Application.destroy() should have force, no_wait, destroy_storage options

### ISSUE THREAD

**Issue by PietroPasotti** [juju/python-libjuju#645]
I would expect the api to reflect more closely the juju cli.
In particular I would expect Application.destroy() to expose options equivalent to `--force --no-wait --destroy-storage`, or to make clear in the docstring why it doesn't and what the actual behaviour is equivalent to.

**Comment by SimonRichardson** [comment]
We'd need to validate all the options individually but seems like a valid request.
