### ISSUE TITLE
We don't interpret all errors from the api as errors

### ISSUE THREAD

**Issue by petevg** [juju/python-libjuju#65]
I am currently trying to troubleshoot any issue deploying the haproxy charm via python-libjuju. While troubleshooting, I discovered that the call to .Deploy in the Application facade doesn't always throw an error when the websocket interface returns an error. I suspect that this problem exists in the other facades as well.

Here's an example of an error that python-libjuju does catch (where by "catch", I mean that it throws a JujuAPIError):

```
client << Frame(fin=True, opcode=1, data=b'{"request-id":6,"error":"json: cannot unmarshal object into Go value of type string
","response":{}}')
```

Here's an example of an error that produces no JujuAPIError:

```
 client << Frame(fin=True, opcode=1, data=b'{"request-id":6,"response":{"results":[{"error":{"message":"cannot parse settings d
ata: yaml: unmarshal errors:\\n  line 1: cannot unmarshal !!str `queue 6...` into charm.Settings\\n  line 2: cannot unmarshal !!str `True` into charm.Settings\\n 
 line 3: cannot unmarshal !!str `0.0.0.0/0` into charm.Settings\\n  line 4: cannot unmarshal !!str `haproxy` into charm.Settings\\n  line 5: cannot unmarshal !!st
r `` into charm.Settings\\n  line 6: cannot unmarshal !!str `backports` into charm.Settings\\n  line 7: cannot unmarshal !!str `SELFSIGNED` into charm.Settings","
code":""}}]}}')
```

Note that, with the second one, we get a `response` key rather than an `error` key, but we have an `error` in the embedded `results` dict.

This is an inconsistency on the websocket api's part, but we should probably work around it here.

**Comment by johnsca** [comment]
Perhaps there is a meaningful distinction, though, between API-level errors (errors in the communication protocol itself) vs error responses?  I had `BundleHandler` raise a `JujuError` if there were response-level errors because this seemed more appropriate than an API error.  I do agree though that the Pythonic thing to do on an error like this is to raise an exception of some sort, but I'm not sure if we could reasonably do this in a generic way?

**Comment by petevg** [comment]
@johnsca It might be interesting to include a .raise_for_status equivalent in python-libjuju. So an api level error would make a JujuError no matter what, but .raise_if_error would raise an Exception if there was a truthy error key in the results.

**Comment by johnsca** [comment]
The problem is that there isn't much consistency at what level the `error` key lies.  Though there also aren't that many cases, so maybe we could handle it.

If we can do it in a generic fashion, I'd prefer to just always raise, as it guarantees to make errors more obvious.

**Comment by petevg** [comment]
@johnsca I think that the right thing to do is to check to see if our message is an ErrorResult, or ErrorResults class. Unfortunately, the latter check is broken due to https://github.com/juju/python-libjuju/issues/71 -- there might be a PR coming from me shortly that fixes a lot of this stuff :-)

**Comment by petevg** [comment]
I'm working on a fix for this, as part of my workk on https://github.com/juju/python-libjuju/issues/67

**Comment by petevg** [comment]
PR here: https://github.com/juju/python-libjuju/pull/74
