### ISSUE TITLE
`add_unit`(s) should call `scale` for container-based charms

### ISSUE THREAD

**Issue by sed-i** [juju/python-libjuju#651]
Calling `add_units` on a sidecar charm, 

```python
await ops_test.model.applications[app_name].add_units(count=1)
```

[results in](https://github.com/canonical/alertmanager-k8s-operator/runs/5518121460?check_suite_focus=true#step:4:672)
```
juju.errors.JujuAPIError: adding units to a container-based model not supported
```

It should probably just call `scale(scale_change=count)` for k8s?

**Comment by juanmanuel-tirado** [comment]
I think you're right. In the case of sidecar charms you have to set the `scale_charm` param.
