### ISSUE TITLE
`Model.get_status` returns outdated unit address

### ISSUE THREAD

**Issue by sed-i** [juju/python-libjuju#675]
I am using a helper function to obtain a unit's IP address:

```python
async def unit_address(ops_test: OpsTest, app_name: str, unit_num: int) -> str:
    status = await ops_test.model.get_status()
    return status["applications"][app_name]["units"][f"{app_name}/{unit_num}"]["address"]
```

It appears that "address" remains the same across a charm upgrade.

**Comment by juanmanuel-tirado** [comment]
Could you provide some code to reproduce?

**Comment by sed-i** [comment]
The reason for the behavior I was seeing is that when I `juju upgrade` a 2-unit app, in `juju status` everything is `active/idle`.
40 seconds in, `unit/1` gets upgraded. Another 40-70 seconds in, `unit/0` gets upgraded.
So with `idle_period=60`, the test was occasionally progressing before all the units finished upgrading.

Increasing `wait_for_idle`'s `idle_period` to 90 sec fixed this.

(For integration tests it would have been nice to know if there's anything pending that didn't happen yet instead of plugging arbitrary `idle_period`, but that's a different story.)

Closing.
