### ISSUE TITLE
v.3.0.0: AttributeError: 'ActionFacade' object has no attribute 'EnqueueOperation'

### ISSUE THREAD

**Issue by sed-i** [juju/python-libjuju#705]
With [pylibjuju 3.0.0](https://github.com/canonical/prometheus-k8s-operator/runs/7771894069?check_suite_focus=true#step:5:31) there is now a [facade error](https://github.com/canonical/prometheus-k8s-operator/runs/7771894069?check_suite_focus=true#step:5:1394):

```
   File "/home/runner/work/prometheus-k8s-operator/prometheus-k8s-operator/.tox/integration/lib/python3.8/site-packages/juju/unit.py", line 233, in run_action
    res = await action_facade.EnqueueOperation(actions=[client.Action(
AttributeError: 'ActionFacade' object has no attribute 'EnqueueOperation'
```

**Comment by cderici** [comment]
Yeah I'm currently working on a fix on actions that'll solve this one as well, thanks for reporting :+1:
