### ISSUE TITLE
Allow `model.wait_for_idle` to wait for 0 units (i.e. verify scale down) 

### ISSUE THREAD

**Issue by MiaAltieri** [juju/python-libjuju#721]
I want to be able to scale an application down to zero units _without_ removing the application itself. I was hoping to use 
```
    await ops_test.model.wait_for_idle(
        apps=[app], timeout=1000, wait_for_exact_units=0
    )
```
to wait for the unit to run all of it's depature/removal/etc hooks, but this doesn't work I think it is due to the `> 0` operator [here](https://github.com/juju/python-libjuju/blob/dacbf6556259000c0d39bc59d00b2d65f8ff73ad/juju/model.py#L2615) perhaps changing it to a `>= 0` would resolve this?

**Comment by MiaAltieri** [comment]
Feel free to close this and not address it, I found a simple workaround
```
    await ops_test.model.block_until(
        lambda: len(ops_test.model.applications[app].units) == 0, timeout=1000
    )
```

**Comment by cderici** [comment]
I think this should be possible with `wait_for_exact_units=0`, thanks for pointing it out, PR coming up soon :+1:
