### ISSUE TITLE
[Bug]: Pass a 'series' kwarg to Model.deploy() error when series is specified

### ISSUE THREAD

**Issue by arturo-seijas** [juju/python-libjuju#758]
### Description

Hi,
All of our iur integration tests are failing in CI with the following error although the `series` parameter is specified when deploying.

`juju.errors.JujuError: Couldn't determine series for charm at /home/runner/work/indico-operator/indico-operator/.tox/integration/tmp/pytest/testing0/charms/indico_ubuntu-20.04-amd64.charm. Pass a 'series' kwarg to Model.deploy().`

If we pin the version to 3.0.2 the error isn't raised.
It look like this issue was introduced in this [PR](https://github.com/juju/python-libjuju/pull/746/files).

Also, it is my understanding that, given I'm deploying kubernetes charms, the series should be irrelevant.

Thank you

### Urgency

Annoying bug in our test suite

### Python-libjuju version

3.0.3

### Juju version

2.9.35

### Reproduce / Test

```python
# Deploy relations first to speed up overall execution
    hello_kubecon_app_name = "hello-kubecon"
    await ops_test.model.deploy(hello_kubecon_app_name)

    # Build and deploy ingress
    charm = await ops_test.build_charm(".")
    application = await ops_test.model.deploy(
        charm, application_name=app_name, series="focal", trust=True
    )
    await ops_test.model.wait_for_idle()
```
```

**Comment by juanmanuel-tirado** [comment]
I have checked the value of `series` using both 2.9 and 3.0 controllers and the value matches the input argument when using 2.9 or 3.0 controllers. The final call to the Juju API client uses the given input argument. I'm checking what's going on there.

**Comment by jameinel** [comment]
For Juju 3.0, I would expect that you should be passing a Base not a
Series. Likely we should move the Lib to Base, and have a compatibility
where if you supply one or the other we translate in the short term. (eg,
we can have pylibjuju 3.0 only take a Base, but translate it to a series
for juju 2.9)

John
=:->

**Comment by juanmanuel-tirado** [comment]
There is something else going on there because this has skipped our CI checks.

**Comment by jnsgruk** [comment]
Related to #759

**Comment by mthaddon** [comment]
> I have checked the value of `series` using both 2.9 and 3.0 controllers and the value matches the input argument when using 2.9 or 3.0 controllers. The final call to the Juju API client uses the given input argument. I'm checking what's going on there.

Have you tried this with a local charm? This is what's failing for us specifically on juju 2.9 with python-libjuju 3.0.3.

**Comment by juanmanuel-tirado** [comment]
There is an ongoing problem with the `Base` object definition. We are unfortunately taking the former 2.9 client version instead of the new 3.0.3. I could have a correct deployment by changing forcing this manually.

**Comment by cderici** [comment]
> There is an ongoing problem with the `Base` object definition. We are unfortunately taking the former 2.9 client version instead of the new 3.0.3. I could have a correct deployment by forcing this manually.

This is incorrect. I just double checked and confirmed that the pylibjuju indeed gets the correct object from correct client modules for both `2.9.35`, `2.9.36` and `3.0.0`.

@jameinel For Juju 3.0, we do indeed pass a Base to the Juju API. For local ones, that's constructed [here](https://github.com/juju/python-libjuju/blob/55690bb8e5659c4d7d856e94475350d194318989/juju/model.py#L1799), and for charmhub ones it comes from the `Charms` facade baked into the `CharmOrigin` ([here](https://github.com/juju/python-libjuju/blob/55690bb8e5659c4d7d856e94475350d194318989/juju/model.py#L1772)). Both are passed to the `ApplicationFacade.Deploy` as `charm_origin`.

The confusion is about the `series` parameter itself. So `Juju 2.9.35` uses `ApplicationFacade v14` and `Juju >=2.9.36` use `ApplicationFacade v15`. Deploy in `v14` accepts the `series` parameter as well as taking the `base` --inside the CharmOrigin--.  Deploy in `v15` doesn't accept the `series` parameter and only takes the base. What pylibjuju needs to do is to stop passing the `series` parameter entirely, as @jnsgruk suggested in #759, however, that would break compatibility with the earlier AppFacade versions that do expect the `series` (and maybe even *not* expect the `base`).

To take the `base` ([track/risk] + OS) as an argument from the user is a libjuju design decision that we can have a discussion with @juanmanuel-tirado and @jameinel.

For this particular issue, @arturo-seijas is correct. I do seem to have introduced a logic that ends up ignoring the series argument when it's passed. Fix is coming, I'm on it :+1:
