### ISSUE TITLE
[Bug]: Unable to deploy by series/base on Juju 3.0

### ISSUE THREAD

**Issue by jnsgruk** [juju/python-libjuju#759]
### Description

When using Juju 3.0, it's no longer possible to deploy by series/base.

From speaking with @wallyworld this morning, I think it's because in 3.0 the deploy API no longer accepts series, which is what we're passing [here](https://github.com/juju/python-libjuju/blob/55690bb8e5659c4d7d856e94475350d194318989/juju/model.py#L2073). In 3.0 I believe we should be sending a "base"

### Urgency

Blocker for our release

### Python-libjuju version

3.0.3 and `master`

### Juju version

3.0

### Reproduce / Test

An example of this is can be seen in this [CI run](https://github.com/jnsgruk/parca-operator/actions/runs/3318649190/jobs/5482836881#step:4:98) when the code actually specifies the `jammy` series, python-libjuju actually deploys `focal`. My understanding is that the Juju 3.0 API is likely ignoring the series parameter (code [here](https://github.com/jnsgruk/parca-operator/pull/15/files#diff-08291d7f4ad7b2caecacb6ae26af540ebbaede9fe42d5e8e1b39d2bdefe4c2d4R43))

**Comment by cderici** [comment]
We do send a `base` inside the `charm_origin` after resolving. However, we weren't communicating the series info (passed as argument) to the resolver itself, so the base coming from that is not the correct one. Fix is ready, I'll push it once I'm done with testing :+1:
