### ISSUE TITLE
Revisiting Pylibjuju CI 

### ISSUE THREAD

**Issue by cderici** [juju/python-libjuju#764]
So we sat down with @jack-w-shaw and talked about how we can make the libjuju CI testing great again and came up with the following setup. Earlier we only needed to care about different python versions, now we need to also care about different juju versions, in particular, the `2.9` and `3.0` branches. 

First, in the jenkins jobs below, we make sure pylibjuju works with `3.0` and `2.9` "stable" channels, and we also keep track with the "edge" for both to make sure if anything breaks on the libjuju side for something that's being added to juju (either on 2.9 or 3.0), then we have enough time to fix it right by the time the `edge` goes to the `stable`. 

Note that in these tests we don't care about the Python compatibility, we fix the version to `Python 3`, which is whatever's the latest python version available, and sweep across the juju channels. In the next section we do exactly the opposite.

- 3.0-stable:
          PYTHON_VERSION: "3"
          JUJU_CHANNEL: "3.0/stable"
- 3.0-edge:
          PYTHON_VERSION: "3"
          JUJU_CHANNEL: "3.0/edge"
- 2.9-stable:
          PYTHON_VERSION: "3"
          JUJU_CHANNEL: "2.9/stable"
- 2.9-edge:
          PYTHON_VERSION: "3"
          JUJU_CHANNEL: "2.9/edge"

In these jenkins jobs below we fix the juju channel to the `latest/stable` (and don't care about the other juju channels), and we sweep across the different Python versions to catch any possible breakage coming from the changes in Python itself. @juanmanuel-tirado we didn't include `python 3.6` and `python 3.7` based on what we discussed with you earlier, however it's easy to add'em if we need'em.

- python3.10:
          PYTHON_VERSION: "3.10"
          JUJU_CHANNEL: "stable"
- python3.9:
          PYTHON_VERSION: "3.9"
          JUJU_CHANNEL: "stable"
- python3.8:
          PYTHON_VERSION: "3.8"
          JUJU_CHANNEL: "stable"

We also discussed about a new job to ensure we keep things clear and running for the `pytest-operator` for the charmers. Basically the job is to take an operator and run their integration tests (that uses pylibjuju) as part of our CI against the changes on the libjuju, to make sure nothing's failing there. We decided to use the [zinc-k8s-operator](https://github.com/jnsgruk/zinc-k8s-operator) in the beginning, we might switch it to something else if anyone's got a better alternative. 

Note that this requires some custom work (@jack-w-shaw 's started hacking on it) and some design decisions (e.g. which version of the upstream operator to use? How to update it etc.). It might also require some (possibly unnecessary) attention in the future, if say, the operator's integration tests fail for reasons unrelated to pylibjuju.

We decided to open an issue for the discussion, and once we establish a consensus, then we'll go ahead and give the green light to implement it :+1: 

@juanmanuel-tirado ideas, comments, etc, would be appreciated.

**Comment by cderici** [comment]
I also thought about running the examples to make sure none of it's broken, but that might be unnecessary, as the examples are there to demonstrate the use, rather than to ensure correctness.

**Comment by juanmanuel-tirado** [comment]
Thanks for starting this discussion in an open format. I will add some ideas we have to explore/discuss.
* Python-libjuju is a tool to be used by charmers and other developers. Is for this reason, that I think about running GitHub actions as much as possible. Given the current nature of this library I would say that everything (or almost everything) can be done with actions. This will enable charmers, and other community members to contribute to a better testing.
* We must have canary testing. I envision two types of canary testing both of them running once per day. One should check python-libjuju against edge versions. The other can test the operators.
* We have to think from the beginning how to use cache in GitHub actions, specially to avoid redundant juju/lxd/microk8s installations.

**Comment by juanmanuel-tirado** [comment]
I close this discussion for the moment.
