### ISSUE TITLE
[Feature]: Juju 3 support

### ISSUE THREAD

**Issue by tbaumann** [juju/python-libjuju#767]
### Description

I just saw that juju 3.0 was released and it's breaking practically all cli command compatibility. (Thus breaking a lot of scripts)

Do you already know the effects it has on this library? It it still safe to use if you consider an upgrade to juju 3 eventually?
Or is it perhaps a way to avoid getting everything broken?

### Urgency

Casually wishlisting

### Code I'd Like to Run

```python
Just worried. Nothing specific.
```

**Comment by juanmanuel-tirado** [comment]
Python-libjuju version 3.0.4 supports Juju 3.x. Python-libjuju versions 2.9.x will not support Juju 3.x. I will close this issue. Reopen it if required.
