### ISSUE TITLE
[Bug]: controller.controller_name() return "None" when connecting with endpoints

### ISSUE THREAD

**Issue by agileshaw** [juju/python-libjuju#771]
### Description

When connecting to a controller implicitly or with its name, running [`controller.controller_name`](https://github.com/juju/python-libjuju/blob/master/juju/controller.py#L173) will provide us with the name of the current controller, which is the expected behavior. 

However, when connecting the controller with its endpoint and credentials, `controller.controller_name` returns "None". 

### Urgency

Annoying bug in our test suite

### Python-libjuju version

2.9.11, 3.0.4

### Juju version

2.9.37

### Reproduce / Test

```python
from juju.controller import Controller
import asyncio

async def juju_stats():
    controller1 = Controller()
    await controller1.connect() #implicit connection
    print(controller1.controller_name) # output: controller-name
    await controller1.disconnect()

    controller2 = Controller()
    await controller2.connect(endpoint="<ip>:17070", username="admin",
        password="admin_pass", cacert="ca_cert") # explicit connection with credential values
    print(controller2.controller_name) # output: None
    await controller2.disconnect()

asyncio.run(juju_stats())
```

**Comment by agileshaw** [comment]
This issue still exists in libjuju version 2.9.44.0

**Comment by Maxcode123** [comment]
I'd like to address this issue. I think it should be handled in the connector layer, specifically in the `connect` method of the Connector. As far as I understand this requires to map the `endpoint` argument (or `username` maybe?) to a model (or controller) and then fetch that model's controller. I'm wondering if there's a smarter way than  searching for the specified endpoint in controllers.yaml?

**Comment by agileshaw** [comment]
I tested the sample code with libjuju 2.9.44.1 and confirmed the issue still exists.

**Comment by cderici** [comment]
> I tested the sample code with libjuju 2.9.44.1 and confirmed the issue still exists. Can we reopen this issue?

For sure, looks like it's not very complicated, I'll take a closer look soon 👍

**Comment by cderici** [comment]
#964 closes this.
