### ISSUE TITLE
[Feature]: implementation of `juju run` abstract API or example

### ISSUE THREAD

**Issue by tbaumann** [juju/python-libjuju#779]
### Description

Hi,
I needed to run a command on a bunch of units. I got it to work (code below) but it feels like I'm either doing it wrong or perhaps the API should offer some abstraction to fetch the results.

```python
action = client.ActionFacade.from_connection(model.connection())
results = await action.Run(
    applications=[],
    commands='pwd',
    machines=[],
    timeout=None,
    units=list( units ),
)

tasks = set()
for result in results.results:
    task = asyncio.create_task(model.wait_for_action(result.action.tag))
    tasks.add(task)
done, pending = await asyncio.wait(tasks, return_when=asyncio.ALL_COMPLETED)
for result in done:
   do something with result.result()

```

It feels like I am missing some abstraction in the library. But I can't find it. Perhaps the ActionResults that I get from action.Run() should offer me a helper to await all the results...

### Urgency

Casually wishlisting

### Code I'd Like to Run

```python
resulthandler = await action.Run(
    applications=[],
    commands='pwd',
    machines=[],
    timeout=None,
    units=list( units ),
)
results = await resulthandler.wait_for_results()
```

**Comment by tbaumann** [comment]
or maybe better it should return a awaitable iteratior

**Comment by cderici** [comment]
I think the abstraction you're looking for is the [run](https://github.com/juju/python-libjuju/blob/88eb6c4b85d7d960fdc65b89ac0d5e79ee4cc6bc/juju/unit.py#L189) method on the `unit` object. Check out the [test_run](https://github.com/juju/python-libjuju/blob/88eb6c4b85d7d960fdc65b89ac0d5e79ee4cc6bc/tests/integration/test_unit.py#L65) and [test_run_action](https://github.com/juju/python-libjuju/blob/88eb6c4b85d7d960fdc65b89ac0d5e79ee4cc6bc/tests/integration/test_unit.py#L112) on how to use it. Hope this helps :+1:

**Comment by tbaumann** [comment]
Thank you, yes I saw that one.
But I have a pretty much arbitrary list of units to run the same command on. (Actually the leader unit of a list of applications)
Firing that command off in one go to has a certain charme.

**Comment by tbaumann** [comment]
This is how I solved it in my code.
https://gist.github.com/tbaumann/fadf3f59babbb4bf0ccb1635a282bacd
See handle_action_result in class RemoteColector

It's not very transparent to read. Also odd is how in order to get the full result it needs to await twice in every task
