### ISSUE TITLE
Implement ssh

### ISSUE THREAD

**Issue by abentley** [juju/python-libjuju#79]
For purposes like Matrix's reboot and kill_juju_agent actions, "ssh" is probably less likely to error than "run".

**Comment by sfeole** [comment]
Just a friendly post, This is how I'm utilizing SSH in automated testing with libjuju, it's working great so far. Thanks for the hard work!

<SNIP>

    logging.debug('Prep Host for Kernel Testing, Copy tests to host')
    node = await utils.execute_process(
         'juju', 'scp', '-m', ModelName, '/srv/scalebot/repo/tests/kernelprep.py', 'ubuntu/0:/home/ubuntu/', log=LOG)
    asyncio.sleep(5)
    assert node

    logging.debug('Run the test')
    test = await utils.execute_process(
         'juju', 'ssh', '-m', ModelName, 'ubuntu/0', 'sudo /home/ubuntu/kernelprep.py', log=LOG)

</SNIP>

the kernelprep.py will run the test and generate output. From there I have Jenkins parse it and figure out what to do next.

**Comment by petevg** [comment]
@sfeole You're welcome! It does my little programmer heart good to know that the minutes I spent breaking that logic out into its own routine in libjuju was time well spent :-)
