### ISSUE TITLE
[Bug]: Not all local charm dirs will be correctly deployed

### ISSUE THREAD

**Issue by juanmanuel-tirado** [juju/python-libjuju#797]
### Description

The code implemented to deploy local charms builds a zip file for a given charm directory. This does no longer work for local charms using the SDK (code contained into `src/charm.py`). 

The most simple workaround is to pack the charm using `charmcraft`. However, the experience is incomplete and leads to potential fails. We have to explore two options:
* Ignore this use case. This means, charm dirs are not going to be deployed. The user must built the corresponding charm using `charmcraft`.
* Built a temporal charm with the expected format. For this, the `charmcraft` code can be incorporated into python-libjuju` to avoid duplicating code.

### Urgency

Casually reporting

### Python-libjuju version

Every version up-to-date

### Juju version

3.1-beta1

### Reproduce / Test

```python
from juju.model import Model

m = Model(); await m.connect();

# Deploy the charm packet solution and check how we can generate the 
# secrets as expected. 
await m.deploy("./tests/charm-secret/charm-secret_ubuntu-22.04-amd64.charm")
assert model.units['charm-secret/0'].workload_status == 'active'
secrets = await model.list_secrets(show_secrets=True)
assert secrets.results is not None
assert len(secrets.results) == 1

# Now do exactly the same with the directory instead of
# the packaged charm. 
await m.deploy("./tests/charm-secret/", "charm-secret-dir")

# We will never reach the active status
assert model.units['charm-secret-dir/0'].workload_status == 'active'
```

**Comment by cderici** [comment]
I just realized the secrets support is landed on the master branch https://github.com/juju/python-libjuju/pull/791. And unless it's specifically asked I don't want to bring that on 2.9 (no one there uses secrets afaik anyways).  So this issue will be fixed for >3.x. Changing issue label and milestone.
