### ISSUE TITLE
[Bug]: model.destroy_units signature changed breaking compatability

### ISSUE THREAD

**Issue by addyess** [juju/python-libjuju#811]
### Description

in older versions of this library, the signature of `destroy_units` allows you to delete a list of units like this:

```await model.destroy_units(*list_of_units)```

because it's signature was this:

```python

    async def destroy_unit(self, *unit_names):
        ...

    destroy_units = destroy_unit
```

in newer versions of this library the signature is
```python
    async def destroy_unit(self, unit_id, destroy_storage=False, dry_run=False, force=False, max_wait=None):
        ...
    destroy_units = destroy_unit
```

This `destroy_units` simply no longer works:

a WORKAROUND for the callers is this:
```await asyncio.gather(*(model.destroy_unit(_) for _ in list_of_units))```

but restoring or removing `destroy_units` would be preferred

### Urgency

Annoying bug in our test suite

### Python-libjuju version

3.1.0.1

### Juju version

juju 3.1

### Reproduce / Test

```python
await model.destroy_units(*matched_units)
E       TypeError: Model.destroy_unit() missing 1 required positional argument: 'unit_id'
```

**Comment by juanmanuel-tirado** [comment]
You're right, the function signature was changed deliberately because a `destroy_unit` function should destroy one single unit. Unfortunately, we didn't provide an alternative compatible with the previous signature. We will add a `destroy_units` signature. Sorry for the disruption.
