### ISSUE TITLE
[Bug]: Unable to get status on low bandwidth

### ISSUE THREAD

**Issue by esunar** [juju/python-libjuju#821]
### Description

When testing out application in low bandwidth situations libjuju is unable to get status and hangs indefinitely(usually for big models). If we increase the bandwidth it behaves normal.

Here are two examples of running below code [150KBps](https://github.com/juju/python-libjuju/files/11058918/150.txt) and [300KBps](https://github.com/juju/python-libjuju/files/11058904/300.txt)

### Urgency

Blocker for our release

### Python-libjuju version

2.9.x

### Juju version

2.9.x

### Reproduce / Test

```python
#!/usr/bin/python3
import asyncio
import json
import logging

from juju.model import Controller

DEFAULT_MAX_FRAME_SIZE = 6 ** 24

# partner cloud
# ssh infra1.partner -N -L localhost:17077:10.11.2.164:17070
ENDPOINT = "localhost:17077"
USERNAME = "admin"
PASSWORD = "redacted"
CA_CERT = "redacted"


async def juju_status():
    controller = Controller(max_frame_size=DEFAULT_MAX_FRAME_SIZE)

    await controller.connect(endpoint=ENDPOINT, username=USERNAME, password=PASSWORD,
                             cacert=CA_CERT)
    model = await controller.get_model("openstack")
    status = await model.get_status()
    print(json.dumps(status, default=vars, indent=1))


def main():
    logging.basicConfig(level=logging.DEBUG)

    ws_logger = logging.getLogger('websockets.protocol')
    ws_logger.setLevel(logging.INFO)

    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    task = loop.create_task(juju_status())
    loop.run_until_complete(asyncio.gather(task))


if __name__ == '__main__':
    main()
```

**Comment by juanmanuel-tirado** [comment]
What is the number of apps in the model? This could be a problem in the Juju side rather than python-libjuju itself. Bear in mind that large models will require longer collection times and an endless loop may simply saturate the controller.

**Comment by esunar** [comment]
Large model, however as you can see in the results it is able to collect when the bandwidth is high.
