### ISSUE TITLE
[Bug]: `wait_for_idle` loses connection, continues to report old status

### ISSUE THREAD

**Issue by ca-scribner** [juju/python-libjuju#823]
### Description

During some test runs when using `wait_for_idle`, we will periodically encounter [this transient error](https://github.com/canonical/istio-operators/actions/runs/4568126568/jobs/8062779510?pr=220) where:
* we observe these errors in the logs:
```
ERROR    asyncio:base_events.py:1707 Exception in callback create_task_with_handler.<locals>._task_result_exp_handler(task_name='tmp', logger=None)(<Task finishe...was stopped')>) at /home/runner/work/istio-operators/istio-operators/.tox/integration/lib/python3.8/site-packages/juju/jasyncio.py:64
handle: <Handle create_task_with_handler.<locals>._task_result_exp_handler(task_name='tmp', logger=None)(<Task finishe...was stopped')>) at /home/runner/work/istio-operators/istio-operators/.tox/integration/lib/python3.8/site-packages/juju/jasyncio.py:64>
Traceback (most recent call last):
  File "/home/runner/work/istio-operators/istio-operators/.tox/integration/lib/python3.8/site-packages/juju/jasyncio.py", line 66, in _task_result_exp_handler
    task.result()
  File "/home/runner/work/istio-operators/istio-operators/.tox/integration/lib/python3.8/site-packages/juju/client/facade.py", line 481, in wrapper
    reply = await f(*args, **kwargs)
  File "/home/runner/work/istio-operators/istio-operators/.tox/integration/lib/python3.8/site-packages/juju/client/old_clients/_client3.py", line 835, in Next
    reply = await self.rpc(msg)
  File "/home/runner/work/istio-operators/istio-operators/.tox/integration/lib/python3.8/site-packages/juju/client/overrides.py", line 111, in rpc
    result = await self.connection.rpc(msg, encoder=TypeEncoder)
  File "/home/runner/work/istio-operators/istio-operators/.tox/integration/lib/python3.8/site-packages/juju/client/connection.py", line 638, in rpc
    raise errors.JujuAPIError(result)
juju.errors.JujuAPIError: shared state watcher was stopped

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/runner/work/istio-operators/istio-operators/.tox/integration/lib/python3.8/site-packages/juju/jasyncio.py", line 78, in _task_result_exp_handler
    logger.exception("Task %s raised an exception: %s" % (task_name, e))
AttributeError: 'NoneType' object has no attribute 'exception'
WARNING  juju.model:model.py:1215 Watcher: watcher stopped, restarting
WARNING  juju.client.connection:connection.py:[54](https://github.com/canonical/istio-operators/actions/runs/4568126568/jobs/8062779510?pr=220#step:7:55)7 Receiver: Connection closed, reconnecting
WARNING  juju.client.connection:connection.py:547 Receiver: Connection closed, reconnecting
WARNING  juju.client.connection:connection.py:547 Receiver: Connection closed, reconnecting
```
* we observe the test continues to run, and `wait_for_idle` continues to report we're [waiting on applications to go active/idle](https://github.com/canonical/istio-operators/actions/runs/4568126568/jobs/8062779510?pr=220#step:7:230)
* when the test times out, we see in the failure log collection that [`juju status`](https://github.com/canonical/istio-operators/actions/runs/4568126568/jobs/8062779510?pr=220#step:10:1) reports everything is active idle

I think this means something is breaking in python-libjuju and either silently not recovering, or not recovering but having the errors suppressed in async machinery so pytest does not see it?

### Urgency

Annoying bug in our test suite

### Python-libjuju version

juju==3.0.4

### Juju version

CLI==2.9.42, with agent pinned to 2.9.34

### Reproduce / Test

```python
This is a transient error, today caused by [this test](https://github.com/canonical/istio-operators/blob/main/tests/test_bundle.py#L205)
```

**Comment by juanmanuel-tirado** [comment]
The scary thing here is the "randomness". There is clearly something broken in the way python-libjuju interacts with the AllWatcher interface with Juju, and it looks particularly hard to find and fix. Thanks for the traces, that will help us debugging.

**Comment by ca-scribner** [comment]
Yeah I would not like to be the one hunting this down :D

If i spot other similar failures i’ll link them here in case they give more
clues

**Comment by ca-scribner** [comment]
I think [this failure](https://github.com/canonical/istio-operators/actions/runs/4600513097/jobs/8127200361?pr=218) is another example

**Comment by juanmanuel-tirado** [comment]
I'm running some of this integration tests in my local environment and I can't replicate these connectivity issues. There could be some problems with these deployments using GitHub infrastructure.

Apart from that I've seen some of tests use 2.9.3x agents. Is there a reason for that? I don't think that could be the problem but just in case.

**Comment by ca-scribner** [comment]
I think @beliaev-maksim can speak to what is blocking us from using newer agents.  There were bugs in the past that forced this, and he tried to unpin it last week but still hit some issues.

**Comment by beliaev-maksim** [comment]
Yes, that is basically due to the bug #824

**Comment by cderici** [comment]
Closing this based on https://github.com/juju/python-libjuju/issues/823#issuecomment-1498042488, re-open if still happening.
