### ISSUE TITLE
[Bug]: Model connection hangs when migration is in progress

### ISSUE THREAD

**Issue by agileshaw** [juju/python-libjuju#829]
### Description

When libjuju tries to establish connection to a model that is in the middle of a migration, it outputs the follow error messages and hangs without returning to the main program:
```
unknown facade EnvironUpgrader
unexpected facade EnvironUpgrader found, unable to decipher version to use
Task exception was never retrieved
future: <Task finished name='Task-32' coro=<Model._watch.<locals>._all_watcher() done, defined at /home/ubuntu/.venv/lib/python3.10/site-packages/juju/model.py:1058> exception=JujuAPIError('model migration in progress')>
Traceback (most recent call last):
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/juju/model.py", line 1061, in _all_watcher
    model_config = await self.get_config()
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/juju/model.py", line 2017, in get_config
    result = await config_facade.ModelGet()
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/juju/client/facade.py", line 483, in wrapper
    reply = await f(*args, **kwargs)
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/juju/client/_client2.py", line 10431, in ModelGet
    reply = await self.rpc(msg)
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/juju/client/facade.py", line 656, in rpc
    result = await self.connection.rpc(msg, encoder=TypeEncoder)
  File "/home/ubuntu/.venv/lib/python3.10/site-packages/juju/client/connection.py", line 627, in rpc
    raise errors.JujuAPIError(result)
juju.errors.JujuAPIError: model migration in progress
```

It seems that it is not communicating the exception from the controller to the main libjuju thread. An expected behavior would be to raise the exception back to the main program and either triggers exception handling blocks or exit with unclean code.

### Urgency

Blocker for our release

### Python-libjuju version

2.9.11, 2.9.42.1, 3.0.4

### Juju version

2.9.42

### Reproduce / Test

```python
from juju.controller import Controller
import asyncio

async def juju_stats():
    controller = Controller(max_frame_size=2**27)
    await controller.connect()
    model = await controller.get_model(<model_uuid>)
    status = await model.get_status()
    print(status)
    await model.disconnect()

asyncio.run(juju_stats())
```

**Comment by cderici** [comment]
@agileshaw @SimonRichardson had an interesting question about this earlier, does this come back after the migration is complete? The answer might help us to think about the problem and the proper solution for it. Thanks!

**Comment by cderici** [comment]
@agileshaw Also, you marked this as a `Blocker for our release`, was this by mistake? Because I don' t see how this would block you from making a release. However, if it's actually urgent I'll trust you and prioritize this no problem, just wanted to double check👍 thanks!

**Comment by agileshaw** [comment]
@cderici Thanks for reaching out and for helping with the bug. It never comes back after the migration completion or failure; it would hang indefinitely without retrying or termination.

As for the bug status, it is indeed blocking our release. One of our application, prometheus-juju-exporter is using libjuju to connect models and gather machine information. Due to this bug, the application hangs silently in our production environment.

**Comment by cderici** [comment]
No problem, we got you👍 

> As for the bug status, it is indeed blocking our release. One of our application, prometheus-juju-exporter is using libjuju to connect models and gather machine information. Due to this bug, the application hangs silently in our production environment.

You do know that even after this is bug is fixed it'll fail, right? You're trying to run the `ModelConfig.ModelGet()` from the api during a migration and it'll always fail with the `juju.errors.JujuAPIError: model migration in progress`. You can't run that before the model migration is done.

**Comment by agileshaw** [comment]
Yes, I'm aware of it. We have exception handling in our application. What we want to see is an exception raised by libjuju being returned to the main program so the logic implemented in our application gets triggered. Hanging is the critical problem here because it give a false sense that the program is running correctly when it is not.
