### ISSUE TITLE
[Bug]: Application Version not reported

### ISSUE THREAD

**Issue by addyess** [juju/python-libjuju#842]
### Description

the `VERSION` field reported in juju status (3.21.4) is not available in the model data supplied by `juju==3.1.0.1`
```
❯ juju status
Model               Controller       Cloud/Region    Version  SLA          Timestamp
validation-upgrade  addyess-vsphere  vsphere/Boston  3.1.2    unsupported  10:25:35-05:00

App                       Version       Status  Scale  Charm                     Channel    Rev  Exposed  Message
calico                    3.21.4        active      2  calico                    1.27/beta   82  no       Calico is active
...
```

```python
> model.applications["calico"].data
{'model-uuid': 'c3f97a27-f824-4b5f-8...c82f2ffc30', 'name': 'calico', 'exposed': False, 'charm-url': 'ch:amd64/jammy/calico-82', 'owner-tag': '', 'life': 'alive', 'min-units': 0, 'constraints': {}, 'config': {'vxlan': 'Always'}, 'subordinate': True, 'status': {'current': 'unset', 'message': '', 'version': ''}, 'workload-version': ''}

perhaps it should be available in the `workload-version` field

```

### Urgency

Annoying bug in our test suite

### Python-libjuju version

3.1.0.1

### Juju version

3.1.2

### Reproduce / Test

In this case, I deployed the calico charm which is a subordinate of a few others -- kind of complicated. 

But it fails with any charm reporting a version with `application-set-version` on the agent. 

the same failure sure occur with the ubuntu charm:

```bash
App     Version  Status  Scale  Charm   Channel  Rev  Exposed  Message
ubuntu  20.04    active      1  ubuntu  stable    22  no 

Unit       Workload  Agent  Machine  Public address  Ports  Message
ubuntu/0*  active    idle   0        10.246.154.122         

Machine  State    Address         Inst id        Base          AZ  Message
0        started  10.246.154.122  juju-cc0cc9-0  ubuntu@20.04      poweredOn
```

```python
assert model.applications["ubuntu"].data["workload-version"] == "20.04"
```

**Comment by addyess** [comment]
FYI, this works correctly in `juju==3.0.4` with a `2.9.x` controller

**Comment by addyess** [comment]
This doesn't seem to occur on fresh `3.1.2` deployments -- but only on a deployment i've upgraded from a prior controller upgrade.  I'm considering bootstrapping a new controller and see if the issue goes away

**Comment by juanmanuel-tirado** [comment]
If this is no longer happening after a fresh installation I will close the issue. Feel free to reopen if it happens again. 

Thanks for reporting.
