### ISSUE TITLE
[Bug]: model.deploy does not behave like juju command

### ISSUE THREAD

**Issue by amandahla** [juju/python-libjuju#863]
## Environment
juju 2.9.42
juju==3.0.4

## Scenario

1. Channel latest/table and series focal (20.04) are available at [PostgreSQL-K8S Charmhub](https://charmhub.io/postgresql-k8s)

2. The command `juju deploy postgresql-k8s --channel=latest/stable --series=focal` deploys the charm postgresql-k8s as expected:
juju deploy output:
```
Located charm "postgresql-k8s" in charm-hub, revision 20
Deploying "postgresql-k8s" from charm-hub charm "postgresql-k8s", revision 20 in channel latest/stable on focal
```

juju status output:
```
juju status
Model      Controller   Cloud/Region        Version  SLA          Timestamp
indico-18  github-pr-2  microk8s/localhost  2.9.42   unsupported  14:37:37-03:00

App             Version  Status   Scale  Charm           Channel        Rev  Address  Exposed  Message
postgresql-k8s           waiting      1  postgresql-k8s  latest/stable   20           no       agent initializing

Unit               Workload     Agent      Address  Ports  Message
postgresql-k8s/3*  maintenance  executing                  (install) installing charm software
```
3. But deploying it while running an integration test using `ops_test.model.deploy("postgresql-k8s",series="focal", channel="latest/stable")` throws an error: 
```
juju.errors.JujuError: Series focal not supported for ch:postgresql-k8s. Only ['jammy']
```

## Expected
Deploy the charm postgresql-k8s accordingly to parameters channel latest/stable and series focal.

## Reference
https://discourse.charmhub.io/t/juju-operators-for-postgresql-and-mysql-are-now-stable/10223/4

### Urgency

Annoying bug in our test suite

### Python-libjuju version

3.0.4

### Juju version

2.9.42

### Reproduce / Test

```python
ops_test.model.deploy("postgresql-k8s",series="focal", channel="latest/stable")
```

**Comment by amandahla** [comment]
Hi @juanmanuel-tirado thanks. But I tried now with juju 2.9.42.3 and got a different error this time:
```juju.errors.JujuError: resolving retry error: No revision was found in the Store.```

**Comment by juanmanuel-tirado** [comment]
Sorry, I think I tested this issue with the wrong branch.

We have a regression in the 2.9 branch. I can confirm this works in 3.1 and master branches.

We have to check what is going on there. We need a backport and a new release with the corresponding fix. I will put some priority on this.
