### ISSUE TITLE
Destroy_controller

### ISSUE THREAD

**Issue by mhmoerma** [juju/python-libjuju#88]
The destroy controller function does not destroy the controller. It removes all the models, but does not remove the controller model. This model remains in status terminating, so the controller never get's removed.

**Comment by petevg** [comment]
Matrix periodically has trouble destroying models. The interesting thing is that I have trouble if I interrupt matrix, then destroy the model that it created with the command line tools.

I suspect that this is a bug in core. We might be triggering it with something that we do when we setup a model, but it might make sense to file the bug on the core side, especially now that you have a consistent repro case ...

**Comment by petevg** [comment]
I just upgraded to the latest juju alpa (juju 2.2-alpha), and the leftover models went away.

I think that this is an issue w/ juju core, that is solved by upgrading.

**Comment by mhmoerma** [comment]
Ok, thanks! I'll test this when juju2.2 goes into stable.

**Comment by mhmoerma** [comment]
Now the command can't delete the controller model. The call succeeds (with destroy_all_models=True) and removes all models, but juju status on the controller model shows `attempt 1 to destroy model failed (will retry):  model not empty, found 1 machine(s)  unsupported`

**Comment by johnsca** [comment]
It looks like this may be expected; after using the `DestroyController` API, the Juju CLI also [calls](https://github.com/juju/juju/blob/develop/cmd/juju/controller/destroy.go#L255) `environ.DestroyController` which hooks directly into provider code ([e.g.](https://github.com/juju/juju/blob/develop/provider/maas/environ.go#L2024)) to actually remove the controller itself.  It seems like this is a bit of a chicken-and-egg issue and a situation, like bootstrapping, where it's just not feasible to reimplement everything the CLI does outside of interacting with the API and we should just defer back to the CLI instead.

@mjs  Am I understanding the scope of what the CLI is doing here correctly?

**Comment by juanmanuel-tirado** [comment]
This issue is five years old.
