### ISSUE TITLE
[Bug]: charm upgrade does not work

### ISSUE THREAD

**Issue by esunar** [juju/python-libjuju#883]
### Description

 when I try to run the below code I got the following error.

```
await model.connect()
app = model.applications["keystone"]
await app.upgrade_charm(channel="victoria/stable")
```
`juju.errors.JujuError: while adding pending resource info for "policyd-override": bad resource metadata: bad info: bad metadata: resource missing filename`

Hower below code runs succesfully. What could be the problem?
```
juju refresh --channel victoria/stable  keystone
```

[log](https://pastebin.canonical.com/p/XPDcg26jTV/) , [code](https://pastebin.canonical.com/p/6hkr32qbxs/), [bundle](https://pastebin.canonical.com/p/qVHybXyTvP/), [thread](https://chat.charmhub.io/charmhub/pl/d4bcykjbajre9ktr9pmj117dgy)

juju client: 2.9.43-ubuntu-amd64
controller: 2.9.42, python juju==2.9.42.4

@cderici 

### Urgency

Blocker for our release

### Python-libjuju version

2.9.42.4

### Juju version

2.9.43-ubuntu-amd64

### Reproduce / Test

```python
import asyncio
import logging

from juju.model import Model

JUJU_MAX_FRAME_SIZE = 2**30


def setup_logging(log_level: str = "DEBUG") -> None:
    log_formatter = logging.Formatter(
        fmt="%(asctime)s [%(levelname)s] %(message)s", datefmt="%Y-%m-%d %H:%M:%S"
    )
    root_logger = logging.getLogger()
    root_logger.setLevel(log_level)
    if not root_logger.hasHandlers():
        console_handler = logging.StreamHandler()
        console_handler.setFormatter(log_formatter)
        root_logger.addHandler(console_handler)


async def update():
    model = Model(max_frame_size=JUJU_MAX_FRAME_SIZE)
    await model.connect()
    app = model.applications["keystone"]
    await app.upgrade_charm(channel="victoria/stable")


setup_logging()
loop = asyncio.new_event_loop()
loop.run_until_complete(update())
```

**Comment by cderici** [comment]
#884 closes this

**Comment by agileshaw** [comment]
@cderici I just ran into this issue with `ceph-mon` upgrade using libjuju `2.9.44.x` (which should contain the fix). The error message I got was `while adding pending resource info for "alert-rules": bad resource metadata: bad info: bad metadata: resource missing filename`.

I was able to produce a similar error for `keystone` upgrade using the script in bug description as well. My juju controller version  is 2.9.44. 

Could you to take a look at this issue again?

**Comment by cderici** [comment]
@agileshaw yeah no problem, I'll re-open the issue and see what's happening as soon as I can 👍

**Comment by cderici** [comment]
#960 closes this.
