### ISSUE TITLE
[Feature]: add `.name` to `Model` for 2.9 branch

### ISSUE THREAD

**Issue by sed-i** [juju/python-libjuju#893]
### Description

In our set of matrix tests, all the tests on Juju 2.9 [fail](https://github.com/canonical/cos-lite-bundle/actions/runs/5406674418/jobs/9823830823) for:
```
AttributeError: 'Model' object has no attribute 'name'
```
CI for Juju 3.2 passes as expected.

This means that tests that use `Model.name` are not portable from v3.2 to v2.9.

In the meanwhile, I could use [`ops_test.model_name` ](https://github.com/charmed-kubernetes/pytest-operator/blob/main/docs/reference.md#model_name) but I was wondering if this could be easily ironed out.

### Urgency

Casually wishlisting

### Code I'd Like to Run

```python
assert (f"/{ops_test.model.name}-loki-0/metrics", "up") in targets_summary
```

**Comment by cderici** [comment]
Closed by #902
