### ISSUE TITLE
Model.connect() does not respect envvar JUJU_MODEL

### ISSUE THREAD

**Issue by aieri** [juju/python-libjuju#909]
If the expectation behind running `connect()` with no parameters is to connect to the model the juju CLI client would operate on, I think it should also respect the JUJU_MODEL environment variable.

More specifically, I think the following inconsistency should be resolved.

In an environment with 2 models, A and B, the following is currently true:
```
$ juju switch A
$ export JUJU_MODEL=B
$ juju status # will return the status of B
$ python3 -m asyncio
[...]
>>> from juju.model import Model
>>> model = Model()
>>> await model.connect()
>>> await model.get_status()  # will return the status of A
```

**Comment by aieri** [comment]
the issue is still relevant and not incomplete

**Comment by aieri** [comment]
the issue is still relevant and not incomplete. Can the bot be disabled for this bug? I will eventually miss the notification and the issue will be lost.

**Comment by cderici** [comment]
@aieri thanks for the heads up, I added the `wishlisted` label so the bot wouldn't touch it.

The reason that we didn't fix this one yet, is that although it's a very simple patch, I don't want this to be solved in a quick and dirty way. One of my side projects is to separate the library part of pylibjuju with the stuff that interacts with these sorts of things. Essentially, pylibjuju is a library, and it should have a pure part that's only concerned with interacting with the Juju API, and on the side it can have a frontend that takes care of things like env variables, repl interaction, stuff like that. That's the reason this is not fixed yet, but it's coming relatively soon.

In the meantime maybe passing `model_name` in `model.connect(model_name=.....)` might help. Having said that, feel free to let us know if this is a common practice for you and it's super annoying, in that case I can try to prioritize this for you 👍

**Comment by aieri** [comment]
Thanks for the explanation @cderici! I only wanted to ensure we don't lose track of this due to an overzealous bot. This bug is not a high priority for us at the moment.

**Comment by dimaqq** [comment]
> [Juju 2.9](https://juju.is/docs/juju/roadmap#juju-juju-29)
> Currently in Security Fix Only support.

The same applies to python-libjuju.

Upgrade to juju 3.x if you can, or use juju cli.
