### ISSUE TITLE
[feature_request] get application public address

### ISSUE THREAD

**Issue by gboutry** [juju/python-libjuju#917]
Hi, is there an easier way of getting an application public address in pylibjuju than:

```python
model = await controller.get_model("openstack")
app_status = await model.get_status(filters=["vault"])
app_status.applications["vault"].public_address
```
Seems like only Unit has `get_public_address` method, not Application.

Something along the lines would be great:
```python
await model.applications["vault"].get_public_address()
```

The application being a K8S charm, I'm interested the SVC address, and not the POD address.

**Comment by gboutry** [comment]
No, that's on 3.2

**Comment by hmlanigan** [comment]
Closed prematurely by the bot.
