### ISSUE TITLE
charm upgrade with switch does not work

### ISSUE THREAD

**Issue by esunar** [juju/python-libjuju#924]
### Description

Trying to achieve same result with
`juju refresh keystone --switch ch:keystone --channel ussuri/stable`

Get error:
juju.errors.JujuError:  : selecting releases: no releases available

[log](https://pastebin.ubuntu.com/p/bKTDyWscn7/), [status.json](https://pastebin.ubuntu.com/p/4PYYGTdm6y/), [bundle](https://pastebin.ubuntu.com/p/kZxd28Sr9Z/)

### Urgency

Blocker for our release

### Python-libjuju version

2.9.44.0

### Juju version

2.9.42

### Reproduce / Test

```python
import asyncio
import logging

from juju.model import Model

JUJU_MAX_FRAME_SIZE = 2**30


def setup_logging(log_level: str = "DEBUG") -> None:
    log_formatter = logging.Formatter(
        fmt="%(asctime)s [%(levelname)s] %(message)s", datefmt="%Y-%m-%d %H:%M:%S"
    )
    root_logger = logging.getLogger()
    root_logger.setLevel(log_level)
    if not root_logger.hasHandlers():
        console_handler = logging.StreamHandler()
        console_handler.setFormatter(log_formatter)
        root_logger.addHandler(console_handler)


async def update():
    model = Model(max_frame_size=JUJU_MAX_FRAME_SIZE)
    await model.connect()
    app = model.applications["keystone"]
    await app.upgrade_charm(channel="ussuri/stable", switch="ch:keystone")


setup_logging()
loop = asyncio.new_event_loop()
loop.run_until_complete(update())
```

**Comment by esunar** [comment]
@cderici

**Comment by esunar** [comment]
The same code worked for `aodh`, `barbican`
However when I try to update `ceilometer`
it gives error:
`juju.errors.JujuAPIError: cannot upgrade application "ceilometer" to charm "ch:amd64/focal/ceilometer-291": would break relation "ceilometer:identity-credentials keystone:identity-credentials"
`
and 
`juju refresh ceilometer --switch ch:ceilometer --channel ussuri/stable`
works without issue.

**Comment by cderici** [comment]
Hey @esunar, sorry I didn't realize this was a blocker for you, I'll take a closer look at this today. 

So this is basically reporting two issues that might be related. One with the `ch:keystone` charm that can't find a replacement, the other one with the `ch:ceilometer` charm that can't do the switch because of an existing integration that needs to be replaced.

For both of these issues, can you tell me what charms have been used for the active applications `keystone` and `ceilometer` ? i.e. we want to replace their charms with `ch:keystone` and `ch:ceilometer`, but what are the previous charms? thanks!

**Comment by esunar** [comment]
I'am trying to change cs:<charm> -> ch:<charm> --channel ussuri/stable

**Comment by esunar** [comment]
ceilometer:
    charm: cs:ceilometer
    channel: stable
    revision: 291
    num_units: 3

**Comment by cderici** [comment]
@esunar Erhan is this issue still valid?

**Comment by esunar** [comment]
> @esunar Erhan is this issue still valid?

In the isolated small bundle it seems to be working. Next week I'll try it on a much complicated bundle and will inform you.
