### ISSUE TITLE
Cloud.py integration

### ISSUE THREAD

**Issue by sebastienpattyn93** [juju/python-libjuju#94]
This is not really an issue but a question on how cloud.py will be integrated to add credentials and bootstrap a controller? Because currently the only way I see to do this is the asyncio wrapper to check output? 

The main reason I'm asking this, is for the following situation: If I manually bootstrap a controller. The default admin password is blank so I can not connect with my controller if I don't want to use the macaroons. Is there any other solution to connect to my controller?

**Comment by johnsca** [comment]
If you wish to change the password of the default admin user, you can use `juju change-user-password`.  However, I think that is unrelated to the question of bootstrapping.

With bootstrapping, I'm not sure I understand where cloud.py would come in to play.  For the time being, at least, bootstrapping is outside the scope of python-libjuju, where the intention is to enable interacting with an existing controller.  Currently, it is only possible to bootstrap via the Juju command-line client, which would require interacting via subprocess (or asyncio.subprocess) and providing the cloud credentials to that.

An alternative to having to bootstrap your own controller is to register with the new Juju-as-a-Service Beta at https://jujucharms.com/ and have the controller be managed for you.  Unfortunately, that does require using macaroons, however, and thus would run up against #50 if you wish to use it entirely without the Juju CLI.

**Comment by sebastienpattyn93** [comment]
Ok thank you. It was the whole bootstrap part that I thought was going to be included in libjuju. Manually bootstrapping a controller will do it for me. About the `juju change-user-password`, I was wondering why it is not possible to do this:

```
        controller = Controller()
        await controller.connect(
            controller_endpoint,
            'admin',
            '', # when bootstrapping admin password is blank
            None,)
        await controller.change_user_password('admin', 'newpassword')
```
I want to connect to a controller with my admin user without changing his password first, So I give an empty password but that is not working.

**Comment by johnsca** [comment]
I think that password is not set to an empty string, but just isn't set, which disables password-based auth and requires macaroon access instead.  I'm not certain, though.  But I do know that if you try to `juju logout` after bootstrap, it will warn that you will lose access to the controller if you don't call `juju change-user-password` first and will reject the logout unless you use `--force`.

**Comment by sebastienpattyn93** [comment]
Ok, then my problem will be fixed normally once I can use the macaroon access.

**Comment by juanmanuel-tirado** [comment]
This issue is five years old.
