### ISSUE TITLE
UserInfo

### ISSUE THREAD

**Issue by mhmoerma** [juju/python-libjuju#95]
Is there a call on controller level to get all the users on the controller?
On model level, the users attribute of a model object returns an empty list, despite the fact there are users with access to this model. 
Is there a way to get the model access for a certain user?

**Comment by tvansteenburgh** [comment]
Hi @mhmoerma, isn't this what your pull request (https://github.com/juju/python-libjuju/pull/89) adds? Or is it something else?

**Comment by mhmoerma** [comment]
@tvansteenburgh It's something else. My pull request adds the possibility get the info of a known user on a controller (so you can get it's controller access). But to get a list of all users on a controller, I didn't find something in the wrapper to provide this. 
And on model level, the info of a model has a property users, but it is always an empty list. So you can't see which users have a certain access on a model

**Comment by johnsca** [comment]
I don't see anything else in the API that looks like it would fetch that information.  We'll need to dive in to the juju CLI source to see how it gathers that info, but it seems like that field should work.

**Comment by mhmoerma** [comment]
Aight, thanks for looking into is.

**Comment by mhmoerma** [comment]
Did you have time to look into this?

**Comment by johnsca** [comment]
I have not had time to look in to this in depth, but it seems from looking at https://github.com/juju/juju/blob/staging/cmd/juju/user/list.go that calling `UserManagerFacade().UserInfo(None, True)` may be what you want.

**Comment by mhmoerma** [comment]
This seems to only return the info of the user used to log in into the controller, not a list of all users. (Tested using the admin to make the connection, and juju cli to create users when logged in as admin)

**Comment by mhmoerma** [comment]
Is there any extra info over this?

**Comment by sebastienpattyn93** [comment]
Is it possible to retrieve a list of all the users with their access on a certain controller?
