### ISSUE TITLE
`unit.destroy(...)` references unit `name` rather than unit `tag`

### ISSUE THREAD

**Issue by addyess** [juju/python-libjuju#950]
I was using `juju==3.2.2` and discovered this issue when running `unit.remove()`

https://github.com/juju/python-libjuju/blame/24db195c11eb7690d6bd562b628a8640e19eb445/juju/unit.py#L114

```diff
-        return await app_facade.DestroyUnit(units=[{"unit-tag": self.name}])
+        return await app_facade.DestroyUnit(units=[{"unit-tag": self.tag}])
```

Discovered when trying to remove a unit

```stacktrace
            if err_results:
>               raise errors.JujuError(err_results)
E               juju.errors.JujuError: ['"etcd/1" is not a valid tag']

.tox/integration/lib/python3.11/site-packages/juju/client/connection.py:692: JujuError
```

**Comment by addyess** [comment]
Yeah, it's still broken right?  Why would this be closed?

**Comment by cderici** [comment]
Hey Adam, yeah looks like this slipped through the cracks and the bot closed it because of inactivity, thanks for the heads up, I'll take care of this soon 👍
