### ISSUE TITLE
python-libjuju support for `set-series` and `upgrade-series`

### ISSUE THREAD

**Issue by gabrielcocenza** [juju/python-libjuju#959]
### Description

Currently it seems that libjuju does not have API support for those juju cli commands. This makes automation of series upgrade with no option rather than using python subprocess to call the juju cli and this is a problem for confined snaps. 

### Urgency

It would save from a weird workaround

### Code I'd Like to Run

```python
>>> from juju.model import Model
>>> model = Model()
>>> await model.connect_current()
>>> keystone = model.applications["keystone"]
>>> keystone.set_series("jammy")

>>> machines =  model.machines
>>> m0 = machines["0"]
>>> m0.upgrade_series("jammy")
```

**Comment by cderici** [comment]
Those functions are deprecated in 2.9 and removed entirely starting from `3.1` as a part of the `series` to `base` transition. New functions are called `set-application-base` and `upgrade-machine`, I will add them, and try to add some base-series utilities to make things easier for you guys 👍
