### ISSUE TITLE
Connecting to a controller/model without password

### ISSUE THREAD

**Issue by ThomasBri** [juju/python-libjuju#96]
In case the controller has no password set, it seems not to be possible to connect to the controller or a model using commands like
`controller.connect('ip-address:port', 'username', '')`
or
`model.connect('ip-address:port', 'model-uuid', 'username', '')`

**Comment by tvansteenburgh** [comment]
To connect to a shared controller you'll need to use macaroon auth: https://pythonhosted.org/juju/narrative/controller.html#connecting-with-macaroon-authentication
