### ISSUE TITLE
Creating model for controller gives unexpected keyword argument 'loop'

### ISSUE THREAD

**Issue by sebastienpattyn93** [juju/python-libjuju#97]
I want to create a new model using libjuju so I executed the following code. in my asyncio loop but It keeps crashing.

```
async def create_model(controller_endpoint, username, password, model): 
    controller = Controller()
    await controller.connect(
        controller_endpoint,
        username,
        password,
        None,)
    await controller.add_model(model)
```
And I got this result: 

```
File "/myscript.py", line 504, in create_model
 await controller.add_model(model)
 File "/usr/local/lib/python3.5/dist-packages/juju/controller.py", line 123, in add_model
 loop=self.loop,
File "/usr/local/lib/python3.5/dist-packages/juju/model.py", line 395, in connect
self.connection = await connection.Connection.connect(*args, **kw)
TypeError: connect() got an unexpected keyword argument 'loop'
```

**Comment by tvansteenburgh** [comment]
Are you running 0.3.0 from pypi, or from source?

**Comment by sebastienpattyn93** [comment]
I've installed libjuju from pypi but I Changed the `model.py` and `controller.py` to the files from source

**Comment by tvansteenburgh** [comment]
Yeah, that's the problem. You should just run from source if you want the latest unreleased stuff. Cherry-picking individual files won't be reliable. What you have now is an old Connection object that can't handle the params that the newer Model and Controller objects are passing to it.
