### ISSUE TITLE
Setting the same secret twice generates a new secret ID

### ISSUE THREAD

**Issue by arturo-seijas** [juju/python-libjuju#970]
### Description

Upon updating a secret with the same value, Juju generates a new secret. This impacts dev experience by requiring charm devs to check if a secret has changed before updating to prevent emitting the same event several times by:
- Storing the secret ID
- Creating a peer relation to store the Id retrieved in step 1 if it doesn't exist
- Comparing the contents of the secret with the new value

This behaviour is also inconsistent with how the relation databags work.

IMO, this operation should be idempotent.

### Urgency

Casually reporting

### Python-libjuju version

3.1.6

### Juju version

3.1.6-genericlinux-amd64

### Reproduce / Test

Run twice the following code
```python

secret = self.app.add_secret({"password": "content"})
logger.error(secret.id)
```

**Comment by cderici** [comment]
@arturo-seijas Thanks for opening the issue, however, this looks like an issue in the ops and/or juju. I.e. not related to pylibjuju. Pylibjuju doesn't have an `add_secret` method.
