### ISSUE TITLE
(Bug in client/connection.py) "raise websockets.exceptions.ConnectionClosed" needs a 'Close' object, not the code and reason directly.

### ISSUE THREAD

**Issue by boltex** [juju/python-libjuju#989]
As per https://websockets.readthedocs.io/en/stable/reference/exceptions.html#websockets.exceptions.ConnectionClosed The parameters need to be 'Close' object, not a number code and reason string as seen on line 483.

https://github.com/juju/python-libjuju/blob/2581b0ced1df6201c6b7fd8cc0b20dcfa9d97c51/juju/client/connection.py#L483

**Comment by cderici** [comment]
Thanks for catching this, @boltex! I think you're right 👍

**Comment by boltex** [comment]
@cderici  No problem! 
Note: The few code bases that create a websockets.exceptions.ConnectionClosed on github have this bug. So chatGPT and copilot propose that same error! ...that's how I got it wrong in my project also and stumbled on your project when trying to see some examples!

**Comment by cderici** [comment]
Closed by #990
